#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import sys
import json
import gzip
import agent
import agent.tasks

agent.set_weight(os.path.basename(__file__), 90)
agent.set_weight('30load', 10)

dump_file = './backup/dump.json.gz'

if not os.path.isfile(dump_file):
    print(f"Cluster backup '{dump_file}' not found", file=sys.stderr)
    sys.exit(1)

# load json from gzip file
fgz = gzip.open(dump_file, mode='r')
dump = json.loads(fgz.read().decode('utf-8'))
fgz.close()

create_retval = agent.tasks.run(
    agent_id=f"cluster",
    action="create-cluster",
    data={
        "network": dump["cluster"]["network"],
        "endpoint": dump["vpn"]["endpoint"],
    },
    endpoint="redis://cluster-leader",
    progress_callback=agent.get_progress_callback(1, 99)
)

if create_retval['exit_code'] != 0:
    print(agent.SD_ERR + f"There was an error during cluster-create. Check the subtask for details.", file=sys.stderr)
    sys.exit(4)
