#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import pwd
import sys
import json
import gzip
import agent
import cluster.backup
import time

dump_file = './backup/dump.json.gz'

# load json from gzip file
fgz = gzip.open(dump_file, mode='r')
dump = json.loads(fgz.read().decode('utf-8'))
fgz.close()

try:
    dump_version = int(dump["version"])
except ValueError:
    dump_version = 3

rdb = agent.redis_connect(privileged=True)

# Restore simple keys
for config in ['network', 'ui_name', 'uuid']:
    rdb.set(f'cluster/{config}', dump['cluster'][config])
    del(dump['cluster'][config])

# Restore favorites
for f in dump['cluster']['favorites']:
    rdb.sadd('cluster/favorites', f)
del(dump['cluster']['favorites'])

# Restore ldap user domains
for d in dump['cluster']['user_domain']['ldap'].keys():
    domain = dump['cluster']['user_domain']['ldap'][d]
    rdb.hset(f'cluster/user_domain/ldap/{d}/conf', mapping=domain['conf'])
    if 'ui_names' in domain:
        rdb.hset(f'cluster/user_domain/ldap/{d}/ui_names', mapping=domain['ui_names'])
    for p in domain['providers']:
        r = rdb.lpush(f'cluster/user_domain/ldap/{d}/providers', p)
    #
    # Advertise new account provider setup
    #
    rdb.publish(os.getenv('AGENT_ID') + '/event/ldap-provider-changed', json.dumps({
        'domain': d,
        'key': f"cluster/user_domain/ldap/{d}/conf",
    }))


del(dump['cluster']['user_domain'])

# Restore backup repositories
for r in dump['cluster']['backup_repository'].keys():
    odest = dump['cluster']['backup_repository'][r]
    if dump_version > 3:
        rclone_conf = odest['rclone_conf']
        restic_password = odest['restic_password']
    else:
        # Convert backup destination data model from old format:
        rclone_conf = cluster.backup.generate_rclone_conf(r, odest['url'], odest['provider'], odest)
        restic_password = odest['password']
    rdb.hset(f'cluster/backup_repository/{r}', mapping={
        "provider": odest['provider'],
        "url": odest['url'],
        "name": odest['name'],
    })
    # Secrets are stored under a private namespace:
    rdb.hset('private/agents/backup_destination/restic_password', r, restic_password)
    rdb.hset('private/nodes/backup_destination/rclone_conf', r, rclone_conf)

# Restore backups, make sure backup_sequence is consistent
max_backup = -1
for b in dump['cluster']['backup'].keys():
    max_backup = max(max_backup, int(b))
    rdb.hset(f'cluster/backup/{b}', mapping=dump['cluster']['backup'][b])
if max_backup > 0:
    # If backup schedules were restored, set the id sequence to protect
    # against id collisions.
    rdb.set('cluster/backup_sequence', max_backup)
    # Restart scheduled backup timers:
    agent.run_helper("systemctl", "restart", "backup-timers.service")

# Restore cluster override for modules
if 'override' in dump['cluster'] and dump['cluster']['override']['modules']:
    rdb.hset(f'cluster/override/modules', mapping=dump['cluster']['override']['modules'])

# Restore subscription info, if present
if 'subscription' in dump['cluster'] and dump['cluster']['subscription']:
    rdb.hset('cluster/subscription', mapping=dump['cluster']['subscription'])

# Restore update policy, if present
if 'apply_updates' in dump['cluster'] and dump['cluster']['apply_updates']:
    rdb.hset('cluster/apply_updates', mapping=dump['cluster']['apply_updates'])

# NOTE: reload of rclone-gateway is implicitly blocking, to avoid races
# with read-backup-repositories
agent.run_helper("systemctl", "reload-or-restart", "rclone-gateway.service")
