#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os
import sys
import json

rdb = agent.redis_connect(privileged=True)
osubscription = rdb.hgetall('cluster/subscription')

if not osubscription:
    sys.exit(0)

if osubscription['provider'] == 'nsent':
    agent.run_helper("systemctl", "start", "send-inventory")
    agent.run_helper("systemctl", "enable", "--now",
        "send-heartbeat.service",
        "send-inventory.timer",
        "send-backup.timer",
    )
    agent.run_helper("systemctl", "start", "send-backup")

elif osubscription['provider'] == 'nscom':
    agent.run_helper("systemctl", "start", "send-inventory")
    agent.run_helper("systemctl", "enable", "--now",
        "send-heartbeat.service",
        "send-inventory.timer",
    )
