#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import base64
import json
import os
import gzip
import subprocess
import sys
import agent

def import_destinations(cluster_backup):
    """Import backup destination configurations into Redis"""
    rdb = agent.redis_connect(privileged=True)
    imported_count = 0
    skipped_count = 0
    local_cluster_uuid = rdb.get("cluster/uuid") or "unknown_local"
    import_cluster_uuid = cluster_backup["cluster"].get("uuid", "unknown_import")
    for dkey, odest in cluster_backup["cluster"]["backup_repository"].items():
        # Check if the destination UUID key exists. Historically, a backup
        # destination was named "backup repository".
        if odest["provider"] == "cluster" and local_cluster_uuid != import_cluster_uuid:
            skipped_count += 1
            continue # internal destination of another cluster, ignore
        elif rdb.exists(f"cluster/backup_repository/{dkey}"):
            skipped_count += 1
            continue
        print("Importing backup destination", dkey, odest["name"], file=sys.stderr)
        # FIXME: validate configuration before storing odest in Redis
        rdb.hset(f"cluster/backup_repository/{dkey}", mapping=odest)
        imported_count += 1
    return imported_count, skipped_count

def main():
    request = json.load(sys.stdin)
    try:
        cipher_data = base64.b64decode(request["backup_data"], validate=True)
    except Exception as ex:
        print(agent.SD_ERR + "backup_data decode error:", ex, file=sys.stderr)
        agent.set_status("validation-failed")
        json.dump([{"error":"invalid_base64","field":"backup_data","parameter":"backup_data","value":""}], fp=sys.stdout)
        sys.exit(2)

    passphrase_fd, wfd = os.pipe()
    os.write(wfd, request["backup_password"].encode("utf-8") + b"\n")
    # NOTE: close wfd, assuming for simplicity that password is few bytes
    # short and fits the pipe buffer size:
    os.close(wfd)
    gpg_cmd = [
        "gpg", "--decrypt", "--batch",
        "--pinentry-mode", "loopback",
        "--passphrase-fd", str(passphrase_fd),
    ]
    gpg_proc = subprocess.run(gpg_cmd,
        input=cipher_data,
        stdout=subprocess.PIPE,
        pass_fds=[passphrase_fd]
    )
    os.close(passphrase_fd)
    if gpg_proc.returncode != 0:
        agent.set_status("validation-failed")
        json.dump([{"error":"invalid_passphrase","field":"backup_password","parameter":"backup_password","value":""}], fp=sys.stdout)
        sys.exit(3)
    json_data = gzip.decompress(gpg_proc.stdout)
    cluster_backup = json.loads(json_data)
    imported_count, skipped_count = import_destinations(cluster_backup)
    json.dump({"imported_destinations": imported_count, "skipped_destinations": skipped_count}, fp=sys.stdout)

if __name__ == "__main__":
    main()
