#!/bin/bash

redis-hgetall "module/${MODULE_ID}/module.env" > ~/module.env
set -a
source ~/module.env
set +a

echo "[DEBUG] $0 Workdir: ${PWD}"
echo "[DEBUG] $0 Event arguments:" "${@}"
echo "[DEBUG] $0 Environment:"
env
echo "[DEBUG] $0 module.env:"
cat ~/module.env

# Calculate the mailbox domain name for Postfix,
# starting from the full host name assigned to the mail pod instance:
printf "MAILBOX_DOMAIN=%s\n" $(cut -f 2- -d . <<<"${HOSTNAME}") >> ~/module.env

cat > ~/dovecot-ldap.conf.ext <<EOF
hosts = ldapproxy:3890
auth_bind = yes
auth_bind_userdn = ${BINDDN:-%u}
base =
scope = base
EOF