#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent.backup
import os

request = json.load(sys.stdin)
restore = agent.backup.Restore(request['module'], request['repository'], request['password'])
env = restore.dump_env()
image_url = env['IMAGE_URL']
# Extract base URL using slice of image_url until the version separator ':', than retrieve the name of the image
# which is the one after the last /
image_id = os.path.basename(image_url[:image_url.index(":")])
node_id = int(request['node'])

# TODO: Mimic add module

# Fake output
print(json.dumps(env))
