#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import agent
import sys
import os
import agent.tasks
import json
import tempfile
import uuid

request = json.load(sys.stdin)

# source
repository = request['repository']
path = request['path']
snapshot = request['snapshot'] or "latest"
replace_requested = request.get('replace', False)

# destination
node_id = int(request['node'])
mvolumes = request.get('volumes', {})

rdb = agent.redis_connect()

# Write the output to a named temporary file, 
# to parse it with the existing read_envfile() function
with tempfile.NamedTemporaryFile() as fenv:
    agent.run_restic(rdb, repository, path, ["--workdir=/srv"], ["dump", snapshot, "state/environment"], text=True, encoding='utf-8', stdout=fenv, check=True)
    fenv.seek(0)
    original_environment = agent.read_envfile(fenv.name)

remove_modules = set()
image_url = original_environment['IMAGE_URL']
source_module_uuid = original_environment.get('MODULE_UUID')
if replace_requested:
    agent.assert_exp(source_module_uuid) # Cannot replace without UUID
# Search for existing instances with the same UUID to remove if
# restore succeedes:
for kmod, kuuid in rdb.hgetall("cluster/module_uuid").items():
    if kuuid == source_module_uuid:
        remove_modules.add(kmod)

image_name = agent.get_image_name_from_url(image_url)
if image_name == 'traefik':
    # Special case: Traefik restoration uses existing instance (no new module created).
    # - Use existing instance for restoration. Restore the backup with a
    #   merge-like strategy, implemented by the module as wanted.
    # - Build fake add-module result to maintain consistent action output format.
    # - Never schedule Traefik for removal to avoid breaking cluster connectivity.
    # - Authorize access to source module's repository.
    module_id = agent.resolve_agent_id("traefik@node", node_id=str(node_id)).removeprefix("module/")
    new_module_uuid = rdb.hget("cluster/module_uuid", module_id)
    agent.assert_exp(new_module_uuid) # Cannot restore without destination UUID
    add_module_result = {
        "output": {
            "module_id": module_id,
            "image_name": image_name,
            "image_url": image_url,
            "module_uuid": new_module_uuid,
        },
        "error": "",
        "exit_code": 0,
    }
    remove_modules = set()
    trx = rdb.pipeline()
    trx.hset('private/nodes/restore_uuid', new_module_uuid, source_module_uuid)
    trx.publish('cluster/event/backup-destination-changed', json.dumps({"destination_ids":[repository]}))
    trx.execute()
else:
    if source_module_uuid and (replace_requested or len(remove_modules) == 0):
        # Force assignment of UUID from the restored environment:
        new_module_uuid = source_module_uuid
    else:
        # Generate a new random UUID:
        new_module_uuid = str(uuid.uuid4())
        # Grant access to source module's repository for restoration:
        rdb.hset('private/nodes/restore_uuid', new_module_uuid, source_module_uuid)
    add_module_result = agent.tasks.run("cluster", "add-module",
        data={
            "image": image_url,
            "node": node_id,
            **({"volumes": mvolumes} if mvolumes else {}),
            "module_uuid": new_module_uuid,
        },
        endpoint="redis://cluster-leader",
        progress_callback=agent.get_progress_callback(2, 15)
    )
    agent.assert_exp(add_module_result['exit_code'] == 0)
    module_id = add_module_result['output']['module_id']

# If restore-module receives a SIGTERM, remove the half-restored module:
remove_module_on_sigterm = {
    "agent_id": "cluster",
    "action": "remove-module",
    "data": {
        "module_id": module_id,
        "force": True,
        "preserve_data": False,
    },
    "extra": {'isNotificationHidden': True},
}

restore_task_result = agent.tasks.run("module/" + module_id, "restore-module",
    data={
        "repository": repository,
        "path": path,
        "snapshot": snapshot,
        "environment": original_environment,
        "replace": replace_requested,
    },
    endpoint="redis://cluster-leader",
    on_sigterm_tasks=[remove_module_on_sigterm],
    progress_callback=agent.get_progress_callback(16, 99 if len(remove_modules) == 0 else 94),
)

if restore_task_result['exit_code'] != 0:
    sys.exit(1)

if replace_requested and remove_modules:
    # Prepare a task list to remove the old modules:
    remove_tasks = []
    for kmod in remove_modules:
        remove_tasks.append({
            "agent_id": "cluster",
            "action": "remove-module",
            "data": {
                "module_id": kmod,
                "preserve_data": False
            },
        })
    # Remove existing modules with the same MODULE_UUID:
    remove_modules_errors = agent.tasks.runp_brief(
        remove_tasks,
        endpoint="redis://cluster-leader",
        progress_callback=agent.get_progress_callback(95, 99)
    )
    agent.assert_exp(remove_modules_errors == 0)

json.dump(add_module_result['output'], fp=sys.stdout)
