#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent
import cluster.backup
import subprocess

def main():
    request = json.load(sys.stdin)
    rdb = agent.redis_connect(privileged=True)

    provider = request['provider']
    destination_uuid = request['id']
    parameters = request.get('parameters', {})

    if not rdb.hget(f'private/nodes/backup_destination/rclone_conf', destination_uuid):
        agent.set_status('validation-failed')
        json.dump([{'field':'id','parameter':'id','value': destination_uuid,'error':'backup_repository_not_found'}], fp=sys.stdout)
        sys.exit(2)

    if provider != rdb.hget(f'cluster/backup_repository/{destination_uuid}', 'provider'):
        agent.set_status('validation-failed')
        json.dump([{'field':'provider','parameter':'provider','value': provider,'error':'backup_provider_mismatch'}], fp=sys.stdout)
        sys.exit(3)

    # The url parameter is optional, if it's missing fetch the value from Redis:
    url = request.get('url') or rdb.hget(f'cluster/backup_repository/{destination_uuid}', 'url')
    if provider == 'cluster':
        rclone_conf = f"[{destination_uuid}]\ntype=local\n"
        destination_basepath = '/srv/repo'
        validation_nodes = set(cluster.backup.lookup_node_from_webdav_url(rdb, url) or '0')
    elif provider == 'rclone':
        if parameters.get('rclone_conf') == "":
            # Configuration Unchanged, replace empty string with the full value read from DB:
            parameters['rclone_conf'] = rdb.hget('private/nodes/backup_destination/rclone_conf', destination_uuid)
        try:
            rclone_conf, url = cluster.backup.sanitize_rclone_conf(destination_uuid, parameters)
        except Exception as ex:
            print(ex, file=sys.stderr)
            agent.set_status('validation-failed')
            json.dump([{'field':'parameters','parameter':'parameters','value':'***','error':'rclone_conf_error'}], fp=sys.stdout)
            sys.exit(2)
        destination_basepath = parameters.get('basepath', rdb.hget(f'cluster/backup_repository/{destination_uuid}', 'basepath') or '')
        validation_nodes = set(rdb.hvals('cluster/module_node'))
    else:
        rclone_conf = cluster.backup.generate_rclone_conf(destination_uuid, url, provider, parameters)
        destination_basepath = cluster.backup.extract_rclone_basepath(url)
        validation_nodes = set(rdb.hvals('cluster/module_node'))
    # Prepare a list of tasks, one for each node, to run in parallel:
    validation_tasks = []
    for node_id in validation_nodes:
        validation_tasks.append({
            "action": "validate-backup-destination",
            "agent_id": f"node/{node_id}",
            "extra": {'isNotificationHidden': True},
            "data": {
                "id": destination_uuid,
                "basepath": destination_basepath,
                "rclone_conf": rclone_conf,
            },
        })
    node_task_results = agent.tasks.runp(
        validation_tasks,
        endpoint="redis://cluster-leader",
    )
    # Fail if all nodes cannot reach the backup repository:
    if all(ntr["exit_code"] != 0 for ntr in node_task_results):
        agent.set_status('validation-failed')
        json.dump([{'field':'parameters','parameter':'parameters','value':'','error':'backup_repository_not_accessible'}], fp=sys.stdout)
        sys.exit(4)

    if 'name' in request:
        rname = request['name']
    else:
        rname = rdb.hget(f'cluster/backup_repository/{destination_uuid}', 'name') or ""

    if not rname:
        rname = cluster.backup.get_default_backup_repository_name(provider, url, destination_uuid)

    if provider != 'rclone':
        # Only rclone provider stores basepath in Redis HASH. Other
        # providers derive its value from the url field and the Redis
        # field is kept as an empty string.
        destination_basepath = ''

    public_data = {'url': url, 'name': rname, 'provider': provider, 'basepath': destination_basepath}
    trx = rdb.pipeline()
    trx.hdel('private/nodes/backup_destination/rclone_conf', destination_uuid)
    trx.hset('private/nodes/backup_destination/rclone_conf', destination_uuid, rclone_conf)
    trx.delete(f'cluster/backup_repository/{destination_uuid}')
    trx.hset(f'cluster/backup_repository/{destination_uuid}', mapping=public_data)
    trx.publish(f"cluster/event/backup-destination-changed", json.dumps({
        "destination_ids": [destination_uuid],
    }))
    if not trx.execute():
        sys.exit(1)

if __name__ == "__main__":
    main()
