#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

import agent
import os

rdb = agent.redis_connect(privileged=True)
node_id = os.environ["NODE_ID"]

# Core 2.1.0 introduces the UDP ports allocation sequence: for backward
# compatibility, set its initial value to be the same of TCP, because the
# latter was used also for UDP allocation until that 2.1.0.
tcpseq = rdb.get(f"node/{node_id}/tcp_ports_sequence")
rdb.setnx(f"node/{node_id}/udp_ports_sequence", tcpseq)
