#!/bin/bash

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2

if [[ ! -d rclone ]] ; then
    # Replace rclone-webdav with the gateway service:
    systemctl disable --now rclone-webdav.service
    rm -vf /etc/systemd/system/rclone-webdav.service \
        /etc/systemd/system/default.target.wants/rclone-webdav.service
    systemctl enable rclone-gateway.service
fi

systemctl restart rclone-gateway.service
