#!/bin/bash

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2
set -e

# Restart subscription long-running services, if enabled
systemctl try-restart node-monitor.service send-heartbeat.service
