#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2
set -e

# Update Python requirements
/usr/local/agent/pyenv/bin/pip3 install -r /etc/nethserver/pythonreq.txt
