#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2

if systemctl -q is-active node-monitor.service; then
    echo "Disabling node-monitor as service"
    systemctl stop node-monitor
    # The disable may fail if the update-core has already removed the service file
    systemctl disable --now node-monitor
    rm -fv /etc/systemd/system/node-monitor.service
    systemctl daemon-reload
fi
