#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import agent
import cluster.grants
import json

request = json.load(sys.stdin)
rdb = agent.redis_connect(privileged=True)

name = request['name']
url = request['url']

if rdb.hgetall(f'cluster/repository/{name}') != None:
    agent.set_status('validation-failed')
    json.dump({'field':'name','parameter':'name','value':name,'error':'repository_same_name_already_exists'}, fp=sys.stdout)
    sys.exit(2)

if rdb.hget(f'cluster/repository/{name}', 'url') != None:
    agent.set_status('validation-failed')
    json.dump({'field':'url','parameter':'url','value':url,'error':'repository_same_url_already_exists'}, fp=sys.stdout)
    sys.exit(2)
