#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import agent
import cluster.grants
import json

request = json.load(sys.stdin)
rdb = agent.redis_connect(privileged=True)

name = request['name']
url = request['url']
# convert boolean to integers
status = 1 if request['status'] else 0
testing = 1 if request.get('testing') else 0

# Add the repository and enable it.
# Access to testing packages is disabled by default.
if not rdb.hset(f'cluster/repository/{name}', mapping={'url': url, 'status': status, 'testing': testing}):
    sys.exit(1)
