#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import agent
import json
import sys
import os

request = json.load(sys.stdin)

images = request['images']
agent_id = os.environ['AGENT_ID']

agent.set_weight('05pullimages', '5')

for image_url in images:
    image_name = agent.get_image_name_from_url(image_url)

    # Transliterate the image name to an environment variable name
    var_name = image_name.translate(str.maketrans('-.+ ', '____')).upper() + '_IMAGE'
    if var_name[0].isdigit():
        # Shell var names cannot begin with a digit. Prepend "I", if necessary.
        var_name = 'I' + var_name

    print(f'Add to {agent_id} environment {var_name}={image_url}', file=sys.stderr)
    agent.set_env(var_name, image_url)

# Start the download
agent.run_helper('podman-pull-missing', *images).check_returncode()
