#!/bin/bash

set -e

mid=$(id -un)
source <(redis-hgetall "${mid}/module.env")

podman pull ${EVENTS_IMAGE:?missing EVENTS_IMAGE in environment}
cid=$(podman create ${EVENTS_IMAGE})
trap "podman rm ${cid}" EXIT

podman export ${cid} | tar -C ~ -x -f -
systemctl --user restart module-agent
