#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

import sys
import json
import agent

request = json.load(sys.stdin)
name = request['zone']

# Delete the zone
agent.run_helper('firewall-cmd', '--permanent', f'--delete-zone={name}').check_returncode()

# Apply the configuration
agent.run_helper('firewall-cmd', '--reload').check_returncode()
