#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

printf "{}\n" # Send output data before stderr redirection

exec 1>&2
set -e

readarray -t input < <(jq -r '.module_id, if .preserve_data then "yes" else "no" end')

mid=${input[0]:?missing module_id argument}
preserve=${input[1]:?missing preserve_data argument}

# A leader node might have it: always clean up the UI root directory:
rm -rf "/var/lib/nethserver/cluster/ui/apps/${mid}"

uid=$(id -u "${mid}" || :)
if [[ -z $uid ]]; then # Rootfull module
    systemctl disable --now agent@"${mid}"
    if [[ ${preserve} == "no" ]]; then
        rm -rf "/var/lib/nethserver/${mid}"
        podman volume ls | grep -o "${mid}-\w*" | xargs -r -- podman volume rm || :
    fi
else # Rootless module
    loginctl disable-linger "${mid}"
    systemctl stop "user@${uid}.service"
    loginctl terminate-user "${mid}" &>/dev/null || :
    # Terminate interactive shells and processes out of lingering sessions:
    killall -s HUP -u "${mid}" || :
    killall -u "${mid}" || :

    if [[ ${preserve} == "yes" ]]; then
        userdel -f "${mid}"
    else
        # Avoid /etc/passwd locking by erasing home directory separately:
        # it is a long operation!
        rm -rf "$(getent passwd "${mid}" | awk -F : '{ print $6 }')"
        userdel -f -r "${mid}"
    fi
fi

# Remove the podman image
podman_image_id=$(REDIS_USER="default" redis-exec hget module/$mid/environment IMAGE_ID)
podman rmi --ignore "$podman_image_id" || :
