#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

exec 1>&2
set -e

readarray -t input < <(jq -r '.module_id, if .preserve_data then "yes" else "no" end')

mid=${input[0]:?missing module_id argument}
preserve=${input[1]:?missing preserve_data argument}

uid=$(id -u "${mid}" || :)
if [[ -z $uid ]]; then # Rootfull module
    systemctl disable --now agent@"${mid}"
    if [[ ${preserve} == "no" ]]; then
        rm -rf "/var/lib/nethserver/${mid}"
    fi
else # Rootless module
    loginctl disable-linger "${mid}"
    systemctl stop "user@${uid}.service"

    if [[ ${preserve} == "yes" ]]; then
        userdel "${mid}"
    else
        userdel -r "${mid}"
    fi
fi
