#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import node.ports_manager
import agent
import json
import sys

request = json.load(sys.stdin)

try:
    # Deallocate TCP and UDP ports
    node.ports_manager.deallocate_ports(request['module_id'], 'tcp')
    node.ports_manager.deallocate_ports(request['module_id'], 'udp')

    # In case of clone/move/import fail ensure rsync port deallocation
    node.ports_manager.deallocate_ports(f"{request['module_id']}_rsync", 'tcp')
except Exception as exc:
    print(agent.SD_WARNING, exc, file=sys.stderr)
