#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import node.ports_manager
import json
import sys

request = json.load(sys.stdin)

# Deallocate TCP and UDP ports
node.ports_manager.deallocate_ports(request['module_id'], 'tcp')
node.ports_manager.deallocate_ports(request['module_id'], 'udp')
