#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

exec 1>&2 # Send any output to stderr, to not alter the action response protocol

#Get the module id of the default Loki instance.

loki_id=$(REDIS_USER=default redis-exec GET cluster/default_instance/loki)

cat >&${AGENT_COMFD} <<EOF
set-env LOKI_URL http://$(REDIS_USER=default redis-exec HGET module/${loki_id}/environment LOKI_ADDR):3100/loki/api/v1/push
dump-env
EOF

install -m 644 "${AGENT_INSTALL_DIR}/promtail.service" "/etc/systemd/system/${MODULE_ID}.service"
systemctl daemon-reload
systemctl enable --now "${MODULE_ID}.service"
