#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import node.ports_manager
import agent
import json
import sys
import os

request = json.load(sys.stdin)

module_env = os.getenv("AGENT_TASK_USER")

if module_env != "" and module_env != f"module/{request['module_id']}":
    print(agent.SD_ERR + f"Agent {module_env} does not have permission to change the port allocation for {request['module_id']}.", file=sys.stderr)
    sys.exit(1)

range = node.ports_manager.deallocate_ports(request['module_id'], request['protocol'])

json.dump(range, fp=sys.stdout)
