#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

exec 1>&2 # Send any output to stderr, to not alter the action response protocol
set -e

install -m 644 "${AGENT_INSTALL_DIR}/samba-dc.service" "/etc/systemd/system/${MODULE_ID}.service"
systemctl daemon-reload

# XXX: Configure roles
redis-exec SADD "${AGENT_ID}/roles/owner" "provision-domain"

# Pull the service image, reading the tag from the local image
tag=$(podman images -f id="${IMAGE_ID}" --format '{{ .Tag }}')
SAMBA_IMAGE="ghcr.io/nethserver/samba-dc:${tag:-latest}"
echo "set-env SAMBA_IMAGE ${SAMBA_IMAGE}" >&${AGENT_COMFD}
podman-pull-missing ${SAMBA_IMAGE}
