#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import sys
import json
import agent
from agent.smarthost import SmartHost


sp = SmartHost()
try :
    smtp = sp.load_smtp()
    json.dump(smtp, fp=sys.stdout)
except Exception as err:
    json.dump([{'field':'get-smarthost','parameter':'get-smarthost','value':err,'error':'cannot_retrieve_smarthost_settings'}],fp=sys.stdout, default=str)
    sys.exit(2)
