#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent
from agent.smarthost import SmartHost


sp = SmartHost()
smtp = sp.load_smtp()
json.dump(smtp, fp=sys.stdout)
