#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

if [[ "${AGENT_EVENT_SOURCE}" != cluster ]]; then
    echo "<4>[WARNING] Invalid event source: ${AGENT_EVENT_SOURCE}" >&2
    exit 2
fi

read -r node_id endpoint < <(jq -r '[.node_id, .endpoint] | join("\t")')

exec /usr/local/sbin/switch-leader --node "${node_id}" --endpoint "${endpoint}"
