#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys

import agent

# Check if event comes from the cluster
if os.getenv("AGENT_EVENT_SOURCE") == 'cluster':
    # parse data
    data = json.load(sys.stdin)
    if 'instance' in data and data['instance'] == 'loki':
        print("Default loki instance changed!")
        agent.run_helper('systemctl', 'try-restart', 'promtail')
