#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import agent
import json
import cluster.grants

#
# Sample input
#{
#    "user": "admin"
#}
#

request = json.load(sys.stdin)
user = request['user']

rdb = agent.redis_connect(privileged=True)

if rdb.execute_command('ACL', 'GETUSER', user) is None:
    json.dump({"field": "user", "parameter": "user", "value": user, "error": "user_not_found"}, fp=sys.stdout) # XXX: implement library function
    agent.set_status('validation-failed')
    sys.exit(2)

rdb.delete(f'roles/{user}')

agent.assert_exp(rdb.execute_command('ACL', 'DELUSER', user) == 1)
# Save ACLs on the disk and propagate to worker nodes
cluster.grants.save_acls(rdb)

print("true")
