#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# This script is used to restart a module's services based on the request received.


exec 1>&2
set -e

readarray -t input < <(jq -r '.module_id')
mid=${input[0]:?missing module_id argument}

if [[ -d /var/lib/nethserver/$mid ]]; then
    # we are rootfull
    systemctl restart "$mid*.service" agent@$mid.service
else
    # we are rootless
    systemctl restart "user@$(id -u "${mid}").service"
fi
