#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import json
import sys
import agent
import cluster.backup

rdb = agent.redis_connect(privileged=True)

brepos = []
password_exists = os.path.isfile('backup/passphrase') and os.stat('backup/passphrase').st_size != 0

for repoid, rclone_conf in rdb.hgetall('private/nodes/backup_destination/rclone_conf').items():
    parameters = rdb.hgetall(f'cluster/backup_repository/{repoid}')
    restic_password = rdb.hget(f'private/agents/backup_destination/restic_password', repoid) or ""
    orepo = {
        "id": repoid,
        "provider": parameters.pop('provider'),
        "name": parameters.pop('name', ''),
        "url": parameters.pop('url'),
        "password": restic_password,
        "parameters": cluster.backup.parse_rclone_params(rclone_conf),
    }
    brepos.append(orepo)


json.dump({"repositories": brepos, "password_exists": password_exists}, fp=sys.stdout)
