#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import json
import sys
import agent

rdb = agent.redis_connect()

brepos = []
password_exists = os.path.isfile('backup/passphrase') and os.stat('backup/passphrase').st_size != 0

for krepo in rdb.scan_iter('cluster/backup_repository/*'):
    parameters = rdb.hgetall(krepo)
    orepo = {
        "id": krepo.removeprefix('cluster/backup_repository/'),
        "provider": parameters.pop('provider'),
        "name": parameters.pop('name', ''),
        "url": parameters.pop('url'),
        "password": parameters.pop('password'),
        "parameters": parameters
    }
    brepos.append(orepo)


json.dump({"repositories": brepos, "password_exists": password_exists}, fp=sys.stdout)
