#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent

# return the module ID of the metrics default instance: eg metrics1

rdb = agent.redis_connect()
module_id = rdb.get(f"node/"+os.environ["NODE_ID"]+"/default_instance/metrics")

json.dump({"metrics_id": module_id}, fp=sys.stdout)
