#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import glob
import json
import os.path

request = json.load(sys.stdin)

core_shortcuts = '/var/lib/nethserver/cluster/ui/shortcuts.json'
ret = []

# Prepare shortcuts from core
if os.path.isfile(core_shortcuts):
    with open(core_shortcuts) as fp:
        shortcuts = json.load(fp)
        for shortcut in shortcuts:
           shortcut["source"] = 'core'
           shortcut["path"] = f'/{shortcut["path"]}'
           ret.append(shortcut)
 
# Prepare shortcuts from applications
for f in glob.glob('/var/lib/nethserver/cluster/ui/apps/*/shortcuts.json'):
    with open(f) as fp:
       shortcuts = json.load(fp)
       for shortcut in shortcuts:
           app = os.path.basename(f.rstrip('/shortcuts.json'))
           shortcut["source"] = app
           shortcut["path"] = f'/apps/{app}/{shortcut["path"]}'
           ret.append(shortcut)

json.dump(ret, fp=sys.stdout)
