#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e
exec 1>&2

# Set default values for the node ldapproxy default instance:
PROXYPORT=3890
LDAPHOST=127.0.0.1
LDAPPORT=389
LDAPSSL=off

# Enable the service at boot
systemctl enable --user ldapproxy

# Persist environment variables in Redis DB:
cat >&${AGENT_COMFD} <<EOF
set-env PROXYPORT ${PROXYPORT}
set-env LDAPHOST ${LDAPHOST}
set-env LDAPPORT ${LDAPPORT}
set-env LDAPSSL ${LDAPSSL}
EOF
