#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import agent
import json
import cluster.grants

#
# Sample input
# [
#    {"on":"cluster", "to":"owner", "action":"*"},
#    {"on":"cluster", "to":"*", "action":"list-*"}
# ]
#

errors = 0
grants = json.load(sys.stdin)
rdb = agent.redis_connect(privileged=True)

for grx in grants:
    try:
        cluster.grants.revoke(rdb, grx['action'], grx['on'], grx['to'])
    except Exception as ex:
        errors += 1
        print(ex, file=sys.stderr)

json.dump({}, fp=sys.stdout)
sys.exit(0 if errors == 0 else 1)
