#!/bin/bash

set -e

# Write the environment for the nsdc.service Systemd unit:
# XXX: add a PREFIX to variable names to avoid PATH injection attacks:
redis-hgetall "module/${MODULE_ID}/module.env" > /usr/local/etc/${MODULE_ID}.env

echo "[DEBUG] $0 Workdir: ${PWD}"
echo "[DEBUG] $0 Event arguments:" "${@}"
echo "[DEBUG] $0 Environment:"
env
echo "[DEBUG] $0 module.env:"
cat /usr/local/etc/${MODULE_ID}.env

# Install the systemd unit
cat - >/etc/systemd/system/${MODULE_ID}.service <<EOF
[Unit]
Description=${MODULE_ID} Samba AD Domain Controller

[Service]
Type=forking
Environment=PODMAN_SYSTEMD_UNIT=%n
EnvironmentFile=/usr/local/etc/${MODULE_ID}.env
Restart=on-failure
TimeoutStopSec=70
# samba exits with 127 on SIGTERM:
SuccessExitStatus=127
ExecStartPre=/bin/rm -f %t/${MODULE_ID}.pid %t/${MODULE_ID}.cid
ExecStart=/usr/bin/podman run \
    --detach \
    --conmon-pidfile %t/${MODULE_ID}.pid \
    --cidfile %t/${MODULE_ID}.cid \
    --cgroups=no-conmon \
    --network=host \
    --cap-drop=all \
    --cap-add=chown,dac_override,dac_read_search,fowner,setgid,setuid,sys_admin \
    --env-file=/usr/local/etc/${MODULE_ID}.env \
    --hostname=\${HOSTNAME} \
    --replace --name=${MODULE_ID} \
    --volume=${MODULE_ID}-data:/var/lib/samba:Z \
    --volume=${MODULE_ID}-config:/etc/samba:Z \
    \${NSDC_IMAGE}
ExecStop=/usr/bin/podman stop --ignore --cidfile %t/${MODULE_ID}.cid -t 10
ExecStopPost=/usr/bin/podman rm --ignore -f --cidfile %t/${MODULE_ID}.cid
PIDFile=%t/${MODULE_ID}.pid

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
