#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Teminate on error
set -e

# Redirect any output to the journal (stderr)
exec 1>&2

# This step will configure official Nextcloud image: https://github.com/docker-library/docs/blob/master/nextcloud/README.md

# Setup default values
NEXTCLOUD_ADMIN_USER="admin"
NEXTCLOUD_ADMIN_PASSWORD="Nethesis,1234"
NEXTCLOUD_TRUSTED_DOMAINS="nextcloud."$(hostname -f)",localhost"

# Read every parameter from stdin. Parameters should be separated by space
# stdin example: "admin password nextcloud.test.org,localhost"
read NEXTCLOUD_ADMIN_USER NEXTCLOUD_ADMIN_PASSWORD NEXTCLOUD_TRUSTED_DOMAINS

# Make sure trusted domains is not empty
if [[ -z "${NEXTCLOUD_TRUSTED_DOMAINS}" ]]; then
  # Validation error
  echo 'set-status validation-failed' >&${AGENT_COMFD}
  exit 2
fi

# Transform from comma separated to space separated
NEXTCLOUD_TRUSTED_DOMAINS=$(echo $NEXTCLOUD_TRUSTED_DOMAINS | tr , " ")

# Talk with agent using file descriptor.
# Setup configuration from user input.
cat >&${AGENT_COMFD} <<EOF
set-env NEXTCLOUD_ADMIN_USER ${NEXTCLOUD_ADMIN_USER}
set-env NEXTCLOUD_ADMIN_PASSWORD ${NEXTCLOUD_ADMIN_PASSWORD}
set-env NEXTCLOUD_TRUSTED_DOMAINS "${NEXTCLOUD_TRUSTED_DOMAINS}"
EOF

# Setup environment for nextcloud app: DB and Redis access
cat >&${AGENT_COMFD} <<EOF
set-env PHP_ENABLE_OPCACHE 1
set-env PHP_MEMORY_LIMIT 512M
set-env MYSQL_DATABASE nextcloud
set-env MYSQL_HOST 127.0.0.1
set-env MYSQL_USER nextcloud
set-env MYSQL_PASSWORD nextcloud
set-env REDIS_HOST 127.0.0.1
set-env REDIS_HOST_PORT 6379
EOF

# Setup extra environment variables for MariaDB, PHP and Nextcloud
cat >&${AGENT_COMFD} <<EOF
set-env MYSQL_ROOT_PASSWORD nextcloud
set-env PHP_MEMORY_LIMIT 512M
set-env OVERWRITEPROTOCOL https
EOF

# Make sure everything is saved inside the environment file
# just before starting systemd unit
cat >&${AGENT_COMFD} <<EOF
dump-env
EOF
