#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#
set -e

exec 1>&2 # Send any output to stderr, to not alter the action response protocol

cat >&${AGENT_COMFD} <<EOF
set-env LOKI_ADDR $(REDIS_USER=default redis-exec HGET node/${NODE_ID}/vpn ip_address)
set-env LOKI_API_AUTH_USERNAME loki
set-env LOKI_API_AUTH_PASSWORD $(uuidgen)
set-env LOKI_LOGS_INGRESS_TOKEN $(uuidgen)
set-env LOKI_HTTP_PORT ${TCP_PORT}
dump-env
EOF
