#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

cat >traefik.yaml <<EOF
http:
  routers:
    loki-log-ingress:
      rule: "Path(\`/loki/api/v1/push\`) && Headers(\`Authorization\`, \`Bearer ${LOKI_LOGS_INGRESS_TOKEN}\`)"
      service: loki
    loki-api:
      rule: "PathPrefix(\`/\`)"
      service: loki
      middlewares:
        - loki-auth
  services:
    loki:
      loadBalancer:
        servers:
        - url: "http://127.0.0.1:3100"
  middlewares:
    loki-auth:
      basicAuth:
        users:
          - "${LOKI_API_AUTH_USERNAME}:$(openssl passwd -apr1 ${LOKI_API_AUTH_PASSWORD})"
EOF
