#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent
import urllib
import traceback
import jsonschema 
import urllib.request

request = json.load(sys.stdin)
rdb = agent.redis_connect(privileged=False)

name = request['name']

# check if the repository exists
if not rdb.hgetall(f'cluster/repository/{name}'):
    agent.set_status('validation-failed')
    json.dump([{'field':'name','parameter':'name','value':name,'error':'repository_not_found'}], fp=sys.stdout)
    sys.exit(2)
