#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import sys
import json
import agent

# parse request
request = json.load(sys.stdin)

# get user
user = request['user']

# check user and reject action
if (user == 'cluster' or '/' in user):
    agent.set_status('validation-failed')
    json.dump([{'field':'user','parameter':'user','value':user,'error':'invalid_user'}], fp=sys.stdout)
    sys.exit(2)

# init redis db
rdb = agent.redis_connect(privileged=True)

# get user info
info = rdb.hgetall('user/' + user)

# return json
json.dump(info, fp=sys.stdout)
