#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#
import os
import sys
import json
import agent

# parse request
request = json.load(sys.stdin)

# get user
user = request['user']

# check user and reject action
if (user == 'cluster' or '/' in user):
    agent.set_status('validation-failed')
    json.dump([{'field':'user','parameter':'user','value':user,'error':'invalid_user'}], fp=sys.stdout)
    sys.exit(2)

# init redis db
rdb = agent.redis_connect(privileged=False)

# get user info
info = rdb.hgetall('user/' + user)

# return json
json.dump(info, fp=sys.stdout)
