#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import sys
import json
import agent

# parse request
request = json.load(sys.stdin)

# get user
user = request['user']

# check user and reject action
if (user == 'cluster' or '/' in user):
    agent.set_status('validation-failed')
    json.dump([{'field':'user','parameter':'user','value':user,'error':'invalid_user'}], fp=sys.stdout)
    sys.exit(2)

# init redis db
rdb = agent.redis_connect(privileged=True)

if rdb.execute_command('ACL', 'GETUSER', user) is None:
    json.dump({"field": "user", "parameter": "user", "value": user, "error": "user_not_found"}, fp=sys.stdout)
    agent.set_status('validation-failed')
    sys.exit(3)

# get user info
info = rdb.hgetall('user/' + user)

response = {}
if 'display_name' in info:
    response['display_name'] = info['display_name']
if 'email' in info:
    response['email'] = info['email']
if 'allowed_networks' in info:
    response['allowed_networks'] = list(filter(None, info['allowed_networks'].split(',')))

# return json
json.dump(response, fp=sys.stdout)
