#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

import os
import agent
import glob

def purge_backup_prom_files(keep_bids):
    """Remove stale backup*.prom files."""
    keep_files = [f'backup{bid}.prom' for bid in keep_bids]
    for prom_file in glob.glob('/run/node_exporter/backup*.prom'):
        if os.path.basename(prom_file) not in keep_files:
            os.unlink(prom_file)
            print("Removed", prom_file)

def main():
    keep_bids = []
    if os.environ["AGENT_EVENT_SOURCE"] != "cluster":
        return
    rdb = agent.redis_connect(use_replica=True)
    for kbk in rdb.scan_iter('cluster/backup/*'):
        bid = kbk.removeprefix('cluster/backup/')
        benabled = rdb.hget(kbk, 'enabled') # returns "1" or ""
        if benabled:
            keep_bids.append(bid)
    purge_backup_prom_files(keep_bids)

if __name__ == "__main__":
    main()