#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent
import os
import cluster.userdomains

rdb = agent.redis_connect(privileged=True)

request = json.load(sys.stdin)

#
# Sample request:
# {
# "domain":"example.com",
# }

domain = request['domain']

domains = cluster.userdomains.get_external_domains(rdb)

if not domain in domains:
    # validation error
    agent.set_status('validation-failed')
    json.dump([{'field':'domain', 'parameter':'domain','value': domain, 'error':'domain_not_found'}], fp=sys.stdout)
    sys.exit(2)

rdb.delete(f"cluster/counters_cache/users/{domain}", f"cluster/counters_cache/groups/{domain}")

protocol = domains[domain]['protocol']

removed_keys = rdb.delete(*list(rdb.scan_iter(f"cluster/user_domain/{protocol}/{domain}/*")))
if removed_keys > 0:
    rdb.publish(os.getenv('AGENT_ID') + '/event/ldap-provider-changed', json.dumps({
        'domain': domain,
        'key': f"cluster/user_domain/{protocol}/{domain}/conf",
    }))
