#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import agent
import json
import sys
import os
import secrets
import string
import cluster.userdomains

request = json.load(sys.stdin)
realm = request['realm'].upper()
hostname = request['hostname'].lower()

if 'REALM' in os.environ:
    print(agent.SD_ERR + "This module is already configured!", file=sys.stderr)
    sys.exit(1)


with agent.redis_connect() as rdb:
    domains = cluster.userdomains.get_internal_domains(rdb)
    kdomain = realm.lower()

    if kdomain in domains:
        provision_type = 'join-domain'
        peer_instance = domains[kdomain]['providers'][0]['id']
        penv = rdb.hgetall(f"module/{peer_instance}/environment")
        nbdomain = penv['NBDOMAIN']
        svcpass = penv['SVCPASS']
    else:
        provision_type = 'new-domain'
        try:
            nbdomain = request['nbdomain'].upper()
        except AttributeError as ex:
            json.dump([{"parameter": 'nbdomain', "value": None, "error": "nbdomain_string_required"}], fp=sys.stdout)
            agent.set_status('validation-failed')
            sys.exit(8)

        # Generate a random password for ldapservice
        alphabet = string.ascii_letters + string.digits + '+-/,.-_^'
        svcpass = ''.join([secrets.choice(alphabet) for i in range(32)])

agent.set_env('PROVISION_TYPE', provision_type)

# Save values of optional parameters
agent.set_env('NBDOMAIN', nbdomain)
agent.set_env('REALM', realm)
agent.set_env('HOSTNAME', hostname + '.' + realm.lower())

# JSON Schema mandatory fields. We are sure they are present.
agent.set_env('IPADDRESS', request['ipaddress'])

agent.set_env('SVCUSER', 'ldapservice')
agent.set_env('SVCPASS', svcpass)

agent.dump_env()
