#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

rdb = agent.redis_connect(use_replica=True)
subscription = rdb.hgetall("cluster/subscription")

if not subscription.get("system_id") or not subscription.get("auth_token"):
    agent.set_status('validation-failed')
    json.dump([{
        "field": "subscription",
        "parameter": "subscription",
        "value": "",
        "error": "subscription_required",
    }], fp=sys.stdout)
    sys.exit(2)
