#!/bin/bash

# Set a new persistent environment variable
echo 'set-env ABC "1 2 3"' >&${AGENT_COMFD}

for progress in $(seq 1 5 100); do
    sleep 0.08
    printf 'set-progress %d\n' $progress >&${AGENT_COMFD}
done

# Begin the expected output string
echo -n n