#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

# Redirect any output to the journal (stderr)
exec 1>&2

# read stdin
# stdin: "mywiki 8081"
read wiki_name tcp_port

# Make sure wiki name is not empty
if [[ -z "${wiki_name}" ]]; then
  # Validation error
  echo "The wiki name is missing" >&2 # FIXME: use UI validationr protocol
  exit 2
fi

# Talk with agent using file descriptor:
# - save environment variables
# - dump everything to file
cat >&${AGENT_COMFD} <<EOF
set-env WIKI_NAME ${wiki_name}
set-env TCP_PORT ${tcp_port}
set-env PHP_ENABLE_OPCACHE 1
dump-env
EOF
