#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Teminate on error
set -e

# Redirect any output to the journal (stderr)
exec 1>&2

# This step will configure Bitnami Dokuwiki image: https://github.com/bitnami/bitnami-docker-dokuwiki

# Setup default values
DOKUWIKI_WIKI_NAME="DokuWiki"
DOKUWIKI_USERNAME="admin"
DOKUWIKI_PASSWORD="Nethesis,1234"
DOKUWIKI_EMAIL="admin@"$(hostname -f)
DOKUWIKI_FULL_NAME="Administrator"

# Read every parameter from stdin. Parameters should be separated by space
# stdin example: "mywiki admin password admin@nethserver.org"
read DOKUWIKI_WIKI_NAME DOKUWIKI_USERNAME DOKUWIKI_PASSWORD DOKUWIKI_EMAIL

# Make sure wiki name is not empty
if [[ -z "${DOKUWIKI_WIKI_NAME}" ]]; then
  # Validation error
  echo "The wiki name is missing" >&2 # FIXME: use UI validationr protocol
  exit 2
fi

# Talk with agent using file descriptor.
# Setup configuration from user input.
cat >&${AGENT_COMFD} <<EOF
set-env DOKUWIKI_WIKI_NAME ${DOKUWIKI_WIKI_NAME}
set-env DOKUWIKI_USERNAME ${DOKUWIKI_USERNAME}
set-env DOKUWIKI_PASSWORD ${DOKUWIKI_PASSWORD}
set-env DOKUWIKI_EMAIL ${DOKUWIKI_EMAIL}
set-env DOKUWIKI_FULL_NAME ${DOKUWIKI_FULL_NAME}
EOF

# Setup PHP with safe defaults
cat >&${AGENT_COMFD} <<EOF
set-env PHP_ENABLE_OPCACHE 1
set-env PHP_MEMORY_LIMIT 512M
EOF

# Make sure everything is saved inside the environment file
# just before starting systemd unit
cat >&${AGENT_COMFD} <<EOF
dump-env
EOF
