#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

agent_id = os.environ['AGENT_ID']

request = json.load(sys.stdin)

rdb = agent.redis_connect(privileged=True)
rdb.set(agent_id + '/ui_note', request['note'])
