#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
from agent.ldapproxy import Ldapproxy
from agent.ldapclient import Ldapclient
import agent

request = json.load(sys.stdin)

domain = Ldapproxy().get_domain(request['domain'])

users = Ldapclient.factory(**domain).list_users()

users = sorted(users, key=lambda rec: rec['user'])
json.dump({"users":users}, fp=sys.stdout)

with agent.redis_connect(privileged=True) as rdb:
    rdb.set(f"cluster/counters_cache/users/{request['domain']}", len(users))
