#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent
import os

#
# Sample request:
# {
# "domain":"example.com",
# "protocol": "ldap",
# "bind_dn": "cn=ldapservice,dc=example,dc=com",
# "bind_password": "s3cret",
# "tls": true,
# "tls_verify": true
# }
request = json.load(sys.stdin)
domain = request['domain']
protocol = request['protocol']

rdb = agent.redis_connect(privileged=True)

if protocol == 'ldap':
    conf = rdb.hgetall(f"cluster/user_domain/ldap/{domain}/conf")
    rdb.hset(f"cluster/user_domain/ldap/{domain}/conf", mapping={
        'bind_dn': request['bind_dn'],
        'bind_password': request['bind_password'],
        'tls': 'on' if request['tls'] else 'off',
        'tls_verify': 'on' if request['tls_verify'] else 'off',
    })

    #
    # Advertise new account provider setup
    #
    rdb.publish(os.getenv('AGENT_ID') + '/event/ldap-provider-changed', json.dumps({
        'domain': domain,
        'key': f"cluster/user_domain/ldap/{domain}/providers",
    }))
    # Advertise new user domain setup
    rdb.publish(os.getenv('AGENT_ID') + '/event/user-domain-changed', json.dumps({
        'domain': domain
    }))
