#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import sys
import agent

rdb = agent.redis_connect()

backups = {}

for kbackup in rdb.scan_iter('cluster/backup/*'):
    bid = kbackup.removeprefix('cluster/backup/')
    battrs = rdb.hgetall(kbackup)

    try:
        schedule_hint = json.loads(battrs.pop("schedule_hint", "{}"))
    except:
        schedule_hint = {}

    backups[bid] = {
        "id": int(bid),
        "name": battrs.pop("name"),
        "repository": battrs.pop("repository"),
        "schedule": battrs.pop("schedule"),
        "schedule_hint": schedule_hint,
        "retention": int(battrs.pop("retention")),
        "instances": [],
        "enabled": bool(battrs.pop("enabled")),
    }

configured_instances = set()

# Collect backup status from all nodes
node_ids = set(rdb.hvals("cluster/module_node"))
backup_statuses = {}  # {(backup_id, module_id): status_dict}
for node_id in node_ids:
    for bid in backups:
        raw = rdb.hgetall(f"node/{node_id}/backup_status/{bid}")
        for mid, status_json in raw.items():
            try:
                backup_statuses[(bid, mid)] = json.loads(status_json)
            except (json.JSONDecodeError, TypeError):
                pass

for bid, backup in backups.items():
    instances = rdb.hget(f"cluster/backup/{bid}", "instances") or ""
    for mid in instances.split():
        module_uuid = rdb.hget("cluster/module_uuid", mid)
        status = backup_statuses.get((bid, mid))
        if status is not None:
            status = dict(status)
            status["success"] = status.pop("errors", 0) == 0
        backup['instances'].append({
            "module_id": mid,
            "ui_name": rdb.get(f"module/{mid}/ui_name") or "",
            "repository_path": module_uuid,
            "status": status,
        })
        configured_instances.add(mid)

unconfigured_instances = []

# The user will not be warned if the following modules have the `no_data_backup` flag.
for mid in rdb.hkeys('cluster/module_node'):
    flags = rdb.smembers(f'module/{mid}/flags')
    if 'no_data_backup' in flags:
        continue
    if not mid in configured_instances:
        unconfigured_instances.append({
            "id": mid,
            "ui_name": rdb.get(f"module/{mid}/ui_name") or "",
        })

json.dump({"backups": list(backups.values()), "unconfigured_instances": unconfigured_instances}, fp=sys.stdout)
