#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import sys

backups = [
    {
        "id": 1,
        "name": "Amazon S3",
        "repository": "d72c200c-52d5-5171-ac9c-45f4e0b684df",
        "schedule": "daily",
        "retention": "30d",
        "instances": [
            {
                "id": "dokuwiki1@b386425e-07bf-4313-8b55-c0e1ed5aa3ea",
                "module": "dokuwiki",
                "instance": "dokuwiki1",
            },
            {
                "id": "nextcloud1@81270f75-16c8-4bef-a4a1-e6014346597a",
                "module": "nextcloud",
                "instance": "nextcloud1",
            }
        ],
    },
    {
        "id": 2,
        "name": "Backblaze 007",
        "repository": "4da89b00-e3a1-57d0-915f-9fb5592c7af8",
        "schedule": "daily",
        "retention": "7d",
        "instances": [
            {
                "id": "dokuwiki1@b386425e-07bf-4313-8b55-c0e1ed5aa3ea",
                "module": "dokuwiki",
                "instance": "dokuwiki1",
            }
        ],
    },
]

json.dump(backups, fp=sys.stdout)