#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e
exec 1>&2

tmpconf=$(mktemp nginx.conf.XXXXXX)
trap "rm -f ${tmpconf}" EXIT

export PROXY_SSL PROXY_SSL_VERIFY PROXY_SSL_VERIFY_DEPTH

if [[ "${TLS}" == "1" ]]; then
    PROXY_SSL="on"
else
    PROXY_SSL="off"
fi

if [[ "${TLS_VERIFY}" == "1" ]]; then
    PROXY_SSL_VERIFY="on"
else
    PROXY_SSL_VERIFY="off"
fi

# Use default value "2", if not already set.
PROXY_SSL_VERIFY_DEPTH=${PROXY_SSL_VERIFY_DEPTH:-2}

envsubst >${tmpconf} <${AGENT_INSTALL_DIR}/nginx.conf.template

# Restart ldapproxy if something has changed in the configuration
if ! diff -q nginx.conf ${tmpconf} ; then
    mv -v ${tmpconf} nginx.conf
    echo "Restart ldapproxy.service"
    systemctl --user restart ldapproxy.service
fi
