#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import agent
import sys
import os

request = json.load(sys.stdin)

agent.set_weight(os.path.basename(__file__), 0) # Validation step, no task progress at all

if request["hostname"] in ["localhost", "localhost4", "localhost6"]:
    agent.set_status('validation-failed')
    json.dump([{'field':'hostname', 'parameter':'hostname','value': request["hostname"], 'error':'forbidden_hostname_value'}], fp=sys.stdout)
    sys.exit(2)
