#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e
exec 1>&2

old_hostname=$(hostname -s)
old_fqdn=$(hostname -f || echo "${old_hostname}")
old_fqdn_re=${old_fqdn//./\.}

read -r hostname domain < <(jq -r '[.hostname, .domain] | join("\t")')

# Raise error, if values are empty
: "${hostname:?}" "${domain:?}"

hostnamectl set-hostname "${hostname}"

# Comment old hostname records in /etc/hosts. If the old hostname appears
# as a localhost alias, it is removed completely.
[[ ${old_hostname} != localhost ]] && sed -i -r \
    -e "/^\s*(127\.0\.0\.1|::1)[^#]*\slocalhost(\s|$)/ { s/\s+${old_fqdn_re}(\s|$)/\1/g ; s/\s+${old_hostname}(\s|$)/\1/g ; b }" \
    -e "/^[^#]+\s${old_hostname}(\s|$)/ s/^/# commented by set-fqdn #/" \
    /etc/hosts

# Append to /etc/hosts according to hostname man page:
printf "127.0.1.1 %s %s\n" "${hostname}.${domain}" "${hostname}" >> /etc/hosts

# write the MOTD and exit
/usr/bin/systemctl start api-server-motd.service
