#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e
exec 1>&2

old_hostname=$(hostname -s)

read -r hostname domain < <(jq -r '[.hostname, .domain] | join("\t")')

# Raise error, if values are empty
: "${hostname:?}" "${domain:?}"

hostnamectl set-hostname "${hostname}"

# For localhost lines (127.0.0.1 or ::1), remove old hostname instead of commenting the line
sed -i -E "/^(127\.0\.0\.1|::1)\s+.*\s(localhost|localhost4|localhost6)(\s|$)/{
    s/\s+${old_hostname}\s+/ /g
    s/\s+${old_hostname}$//
    s/\s+/ /g
}" /etc/hosts

# Comment old hostname records in /etc/hosts (except localhost lines already handled above)
sed -i -E "/^[^#].+\s${old_hostname}(\s|$)/ s/^/# commented by set-fqdn #/" /etc/hosts

# Append to /etc/hosts according to hostname man page:
printf "127.0.1.1 %s %s\n" "${hostname}.${domain}" "${hostname}" >> /etc/hosts

# write the MOTD and exit
/usr/bin/systemctl start api-server-motd.service
