#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import sys
import json
import agent

errors = []

request = json.load(sys.stdin)
rdb = agent.redis_connect(privileged=False)

agent.set_weight(os.path.basename(__file__), 0) # Validation step, no task progress at all

name = request['name']
url = request['url']

# check for duplicate names
if rdb.hgetall(f'cluster/backup_repository/{name}'):
    errors.append({'field':'name','parameter':'name','value':name,'error':'backup_repository_same_name_already_exists'})

# check for duplicate urls
for m in rdb.scan_iter('cluster/backup_repository/*'):
    if rdb.hget(m, 'url') == url:
        errors.append({'field':'url','parameter':'url','value':url,'error':'backup_repository_same_url_already_exists'})

if errors:
    agent.set_status('validation-failed')
    json.dump(errors, fp=sys.stdout)
    sys.exit(2)
