#!/bin/bash -x

#
# Setup wireguard worker node
#

VPN_OUT_DIR=/etc/wireguard
VPN_CONF=$VPN_OUT_DIR/wg0.conf
mkdir -p $VPN_OUT_DIR
chmod 700 $VPN_OUT_DIR

hostname=$(hostname -s)

# Load VPN config variables
source <(redis-hgetall "node/${hostname}/vpn")

# Save private key
if [ ! -f $VPN_OUT_DIR/privatekey ]; then
    umask 0077
    echo $private_key > $VPN_OUT_DIR/privatekey
    umask 0022
fi

# Generate configuration
net=$(echo $IP_ADDRESS | cut -d'.' -f1,2,3)".0"
rm -f $VPN_CONF
cat > $VPN_OUT_DIR/wg0.conf << EOF
[Interface]
Address = $IP_ADDRESS/32
PrivateKey = $(cat $VPN_OUT_DIR/privatekey)

[Peer]
PublicKey = $SERVER_PUBLIC_KEY
Endpoint = $SERVER_PUBLIC_ADDRESS
AllowedIPs = $net/24
PersistentKeepalive = 30
EOF

systemctl stop wg-quick@wg0 &>/dev/null
systemctl enable --now wg-quick@wg0

