#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2
set -e

# Clean up local images that are no longer required by the new module
# version

export LC_ALL=C # required by sort for portability

# Find the images that are no longer required:
# retrieve from env all variable with the prefix PREV_
# remove not used images like PREV_*_IMAGE and PREV_IMAGE_URL
# ignore errors and exit with successful exit status

for varname in ${!PREV_*}; do 
  if [[ $varname =~ _IMAGE$ || $varname =~ _URL$ ]]; then
    podman image rm --ignore ${!varname} 2>/dev/null || :
  fi
done
