#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent
import os.path
import cluster.userdomains

rdb = agent.redis_connect()

request = json.load(sys.stdin)

#
# Sample request:
# {
# "domain":"example.com",
# "protocol": "ldap",
# "host":"18.19.20.21",
# "port": 636,
# "schema": "rfc2307",
# "bind_dn": "cn=ldapservice,dc=example,dc=com",
# "bind_password": "s3cret",
# "base_dn": "dc=example,dc=com",
# "tls": true,
# "tls_verify": true
# }

domain = request['domain']

domains = cluster.userdomains.get_internal_domains(rdb) | cluster.userdomains.get_external_domains(rdb)

agent.set_weight(os.path.basename(__file__), 0) # Validation step, no task progress at all

if domain in domains:
    # validation error
    agent.set_status('validation-failed')
    json.dump([{'field':'domain', 'parameter':'domain','value': domain, 'error':'domain_exists'}], fp=sys.stdout)
    sys.exit(2)
