#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#


import sys
import json
import agent

request = json.load(sys.stdin)
bid = request['id']

proc = agent.run_helper("run-backup", f"--backup={bid}")
if proc.returncode != 0:
    sys.exit(1)
