#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import agent
import sys
import subprocess
import os

outdata = []
module_is_rootfull = os.geteuid() == 0
module_id = os.environ['MODULE_ID']

with subprocess.Popen(['podman', 'volume', 'ls', '--format=json'], stdout=subprocess.PIPE) as vproc:
    for vobj in json.load(vproc.stdout):
        if module_is_rootfull and not vobj['Name'].startswith(module_id + '-'):
            # a rootfull module share the volume namespace with other rootfull modules:
            # skip volumes that do not belong to our MODULE_ID
            continue

        outdata.append(vobj['Name'])

json.dump(outdata, fp=sys.stdout)
