#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent
import cluster.modules

request = json.load(sys.stdin)
rdb = agent.redis_connect(privileged=True)
available = cluster.modules.list_available(rdb)

ret = None

# Prepare variables for later use
for a in available:

    if a["id"] == request["id"]:
        ret = a
        ret.pop('versions', None)
        ret.pop('repository_updated', None)
        break

json.dump(ret, fp=sys.stdout)
