#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import sys
import json
import agent
import ipcalc

# Action summary:
# 1. allocate a VPN IP address for the node
# 2. create redis acls for the node agent

request = json.load(sys.stdin)

node_pwh = request['node_pwh']
assert node_pwh
public_key = request['public_key']
assert public_key
endpoint = request['endpoint']
assert type(endpoint) is str
listen_port = request['listen_port']
assert listen_port

rdb = agent.redis_connect(privileged=True)

#
# 1/a. Retrieve leader_ip_address, required by the new node to complete the
#      join procedure
#
leader_id = rdb.get('cluster/leader')
leader_ip_address = rdb.hget(f'node/{leader_id}/vpn', 'ip_address')
assert leader_ip_address
leader_public_key = rdb.hget(f'node/{leader_id}/vpn', 'public_key')
assert leader_public_key
leader_listen_port = rdb.hget(f'node/{leader_id}/vpn', 'listen_port')
assert leader_listen_port

#
# 1/b. Generate a new node_id and VPN IP address
#
network = ipcalc.Network(rdb.get('cluster/network'))
node_id = str(rdb.incr(f'cluster/node_sequence'))
ip_address = str(network.network() + node_id)

#
# 1/c. Store VPN settings of the new node
#
rdb.hset(f'node/{node_id}/vpn', mapping={
    "public_key": public_key,
    "ip_address": ip_address,
    "endpoint": endpoint,
    "listen_port": str(listen_port),
})

#
# 2. Create redis acls for the node agent
#
redis_grant_node = rdb.execute_command('ACL SETUSER',
    f'node/{node_id}', 'ON', '#' + node_pwh,
    'resetkeys',     f'~node/{node_id}/*',
    'resetchannels', '&progress/task/*',
    'nocommands',    '+@read', '+@write', '+@transaction', '+@connection', '+publish',
    '+psync', '+replconf', '+ping', # for replicas
)
assert redis_grant_node is True

# Add the Wireguard peer configuration
peers = {pkey: rdb.hgetall(pkey) for pkey in rdb.scan_iter('node/*/vpn')}
agent.save_wgconf(leader_ip_address, leader_listen_port, peers)
agent.run_helper(f'wg set wg0 peer {public_key} allowed-ips {ip_address}'.split(' ')).check_returncode()
# XXX agent.run_helper(f'ip route add ')

#
# Return the new information to the caller
#
json.dump({
    "node_id": node_id, # required to set up node agent
    "ip_address": ip_address, # required to set up wg0 device
    "leader_public_key": leader_public_key, # required for VPN auth
    "network": network, # required to set up route table
    "leader_ip_address": leader_ip_address, # required to rewrite /etc/hosts cluster-leader
}, sys.stdout)
