#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent
import cluster.modules

rdb = agent.redis_connect(privileged=True)
available = cluster.modules.list_available(rdb, skip_core_modules = True)
disabled_updates_reason = cluster.modules.get_disabled_updates_reason(rdb)

# Decorate with disabled_updates_reason:
for a in available:
    a["disabled_updates_reason"] = disabled_updates_reason

cluster.modules.decorate_with_installed(rdb, available)
cluster.modules.decorate_with_updates(rdb, available)
cluster.modules.decorate_with_install_destinations(rdb, available)
json.dump(available, fp=sys.stdout)
