#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

cat >&"${AGENT_COMFD}" <<EOF
set-weight 01_validate_web_path 0
EOF

read -r path < <(jq -r '.path')

if [[ -n $TRAEFIK_PATH ]]; then
    if [[ $TRAEFIK_PATH == $path ]]; then 
        exit 0
    # check if the webpath is already in use
    else
        if ! /usr/bin/curl -k -s https://127.0.0.1$path/ | grep '404' > /dev/null; then
            jq -c -n --arg path "${path}" '[{"field":"path","parameter":"path","value":$path,"error":"webpath_already_used_in_traefik"}]'
            echo "set-status validation-failed" >&"${AGENT_COMFD}"
            exit 2
        fi
        exit 0
    fi
# check if the webpath is already in use
else
    if ! /usr/bin/curl -k -s https://127.0.0.1$path/ | grep '404' > /dev/null; then
        jq -c -n --arg path "${path}" '[{"field":"path","parameter":"path","value":$path,"error":"webpath_already_used_in_traefik"}]'
        echo "set-status validation-failed" >&"${AGENT_COMFD}"
        exit 2
    fi
    exit 0
fi
