#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

cat >&"${AGENT_COMFD}" <<EOF
set-weight 01validate_mariadb_tcp_port 0
EOF

read -r mariadb_tcp_port < <(jq -r '.mariadb_tcp_port')

# Check if mariadb_tcp_port is bound to a network interface
if  lsof -i:${mariadb_tcp_port} > /dev/null; then
    jq -c -n --arg mariadb_tcp_port "${mariadb_tcp_port}" '[{"field":"mariadb_tcp_port","parameter":"mariadb_tcp_port","value":$mariadb_tcp_port,"error":"mariadb_tcp_port_does_exist"}]'
    echo "set-status validation-failed" >&"${AGENT_COMFD}"
    exit 2
fi

exit 0
