#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

cat >&"${AGENT_COMFD}" <<EOF
set-weight 01validate_phpmyadmin_hostname 0
EOF

read -r host < <(jq -r '.host')

if [[ -n $TRAEFIK_HOST ]]; then
    if [[ $TRAEFIK_HOST == $host ]]; then 
        exit 0
    # check if the hostname is already in use
    else
        if ! /usr/bin/curl -s -H Host:$host http://127.0.0.1 | grep '404' > /dev/null; then
            jq -c -n --arg host "${host}" '[{"field":"host","parameter":"host","value":$host,"error":"hostname_already_used_in_traefik"}]'
            echo "set-status validation-failed" >&"${AGENT_COMFD}"
            exit 2
        fi
        exit 0
    fi
# check if the hostname is already in use
else
    if ! /usr/bin/curl -s -H Host:$host http://127.0.0.1 | grep '404' > /dev/null; then
        jq -c -n --arg host "${host}" '[{"field":"host","parameter":"host","value":$host,"error":"hostname_already_used_in_traefik"}]'
        echo "set-status validation-failed" >&"${AGENT_COMFD}"
        exit 2
    fi
    exit 0
fi
