#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

if ! /usr/bin/podman volume exists secrets; then
    /usr/bin/podman volume create secrets
    password_phpmyadmin=$(/usr/bin/openssl rand -hex 20)
    echo $password_phpmyadmin > ~/.local/share/containers/storage/volumes/secrets/_data/phpmyadmin.secret
    password_root=$(/usr/bin/openssl rand -hex 20)
    echo $password_root > ~/.local/share/containers/storage/volumes/secrets/_data/root.secret
fi

exit 0
