#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

if [[ ! -d ~/.config/state/secrets ]]; then
    /usr/bin/mkdir -p ~/.config/state/secrets
fi

if [[ ! -f ~/.config/state/secrets/phpmyadmin.secret ]]; then
    password_phpmyadmin=$(/usr/bin/openssl rand -hex 20)
    /usr/bin/echo $password_phpmyadmin > ~/.config/state/secrets/phpmyadmin.secret
    /usr/bin/podman secret create phpmyadmin.secret ~/.config/state/secrets/phpmyadmin.secret
fi

if [[ ! -f ~/.config/state/secrets/root.secret ]]; then
    password_root=$(/usr/bin/openssl rand -hex 20)
    /usr/bin/echo $password_root > ~/.config/state/secrets/root.secret
    /usr/bin/podman secret create root.secret ~/.config/state/secrets/root.secret
fi
