#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent
import os

agent.set_weight(os.path.basename(__file__), 0) # Pre-validation step, no task progress at all

request = json.load(sys.stdin)

original_environment = request['environment']
ipaddress = original_environment['IPADDRESS']

# Ensure a network device with the IPADDRESS exists
os.environ['IPADDRESS'] = ipaddress
agent.run_helper('samba-network', 'up').check_returncode()
