#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
        'PROVISION_TYPE',
        'NBDOMAIN',
        'REALM',
        'IPADDRESS',
        'SVCUSER',
        'SVCPASS',
    ]:
    agent.set_env(evar, original_environment[evar])

# The "samba-tool domain backup restore" procedure expects a new DC hostname,
# a new one must be provided, now!
def generate_new_dc_name(name):
    if len(name) > 1 and (name[-2].isnumeric() and name[-1].isalpha()):
        newname = name[:-2] + \
                alphabet[(1 + alphabet.find(name[-2])) % len(alphabet)] + \
                alphabet[(1 + alphabet.find(name[-1])) % len(alphabet)]

    elif name[-1].isnumeric():
        newname = name + 'r'
    else:
        newname = name + '0'

    if len(newname) > 14:
        newname = newname[:13] + newname[-2:]

    return newname

hname, _ = original_environment['HOSTNAME'].split('.', 1) # short hostname
agent.set_env('HOSTNAME', generate_new_dc_name(hname) + '.' + original_environment['REALM'].lower())

agent.dump_env()
