#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
        'PROVISION_TYPE',
        'NBDOMAIN',
        'REALM',
        'IPADDRESS',
        'SVCUSER',
        'SVCPASS',
    ]:
    agent.set_env(evar, original_environment[evar])

# The "samba-tool domain backup restore" procedure expects a new DC hostname,
# a new one must be provided, now!
dcname, _ = original_environment['HOSTNAME'].split('.', 1) # short hostname
dcname = 'o' + dcname[14::-1] # "o" + reversed short hostname, trimmed at 14 chars max
agent.set_env('HOSTNAME', dcname + '.' + original_environment['REALM'].lower())

agent.dump_env()
