#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

exec 1>&2
set -e

echo "Resume Samba DC state:"
podman run --hostname="${HOSTNAME}" --privileged --interactive --workdir=/var/lib/samba --rm --entrypoint=[] \
    --volume="${MODULE_ID}-config":/etc/samba \
    --volume="${MODULE_ID}-data":/var/lib/samba \
    "${SAMBA_DC_IMAGE}" bash -s <<'EOF'

set -e
nbname=$(hostname -s | tr "[a-z]" "[A-Z]")

samba-tool domain backup restore \
    --backup-file=backup/samba-backup.tar.bz2 \
    --targetdir=restore \
    --newservername=${nbname}

sed "s/netbios name = .*/netbios name = ${nbname}/" restore/etc/smb.conf.orig | tee /etc/samba/smb.conf

rm -rvf private sysvol
mv -v restore/private .
mv -v restore/state/sysvol .
rm -rvf restore backup

EOF

# Enable and start the NSDC service
systemctl enable --now "${MODULE_ID}.service"
