#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

exec 1>&2
set -e

echo "Resume Samba DC state:"
podman run --privileged --interactive --workdir=/srv --rm --entrypoint=[] \
    --volume="${MODULE_ID}-data":/srv \
    "${SAMBA_DC_IMAGE}" bash -s <<'EOF'
find . -type f -name '*.[l,t]db.bak' -print0 | while read -d $'\0' elem ; do
    mv -vf "${elem}" "${elem%.bak}"
done
EOF

# Enable and start the NSDC service
systemctl enable --now "${MODULE_ID}.service"
