#!/usr/bin/env python3

# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#


import agent
import agent.tasks
import os
import sys
import json
import smtplib
import ssl


data = json.load(sys.stdin)

# do not validate if enabled is false
enabled = data['enabled']
if not enabled:
    sys.exit(0)

port =  int(data['port'])
host = data['host']
username = data['username']
password = data['password']
encrypt_smtp = data['encrypt_smtp']
tls_verify = data['tls_verify']


# verify the hostname and the certificate
ctx = ssl.create_default_context()
if tls_verify:
    ctx.check_hostname = True
    ctx.verify_mode = ssl.CERT_REQUIRED
else:
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE

try :
    if encrypt_smtp == 'starttls':
        smtp = smtplib.SMTP(host, port=port, timeout=10)
        smtp.starttls(context=ctx)
    elif encrypt_smtp == 'tls':
        smtp = smtplib.SMTP_SSL(host, port=port, timeout=10, context=ctx)
    else:
        smtp = smtplib.SMTP(host, port=port, timeout=10)

    # we have a login, we try to authenticate.
    if username:
        smtp.login(username, password)
    # without authentication, we have now way to test except 
    # to connect to the server. we quit
    smtp.quit()

except smtplib.SMTPAuthenticationError as err:
    agent.set_status('validation-failed')
    # probably name or password failure
    json.dump([{'field':'test_smarthost','parameter':'test_smarthost','value':err,'error':'cannot_authenticate_to_server'}],fp=sys.stdout, default=str)
    sys.exit(2)

except smtplib.SMTPConnectError as err:
    agent.set_status('validation-failed')
    # any connection error to the server
    json.dump([{'field':'test_smarthost','parameter':'test_smarthost','value':err,'error':'cannot_connect_to_server'}],fp=sys.stdout, default=str)
    sys.exit(3)

except smtplib.SMTPNotSupportedError as err:
    agent.set_status('validation-failed')
    # probably need to use starttls
    json.dump([{'field':'test_smarthost','parameter':'test_smarthost','value':err,'error':'connection_not_supported_by_server'}],fp=sys.stdout, default=str)
    sys.exit(4)

except ssl.SSLCertVerificationError as err:
    agent.set_status('validation-failed')
    # the certificate is not valid probably self-signed or not valid for this hostname
    json.dump([{'field':'test_smarthost','parameter':'test_smarthost','value':err,'error':'valid_certificate_verification_error'}],fp=sys.stdout, default=str)
    sys.exit(5)

except smtplib.socket.gaierror as err:
    print(agent.SD_NOTICE + "smtplib validation:", err, file=sys.stderr)
    agent.set_status('validation-failed')
    json.dump([{'field':'host','parameter':'host','value': host,'error':'address_error'}],fp=sys.stdout, default=str)
    sys.exit(7)

except smtplib.socket.error as err:
    agent.set_status('validation-failed')
    # We have issued a timeout, the server is not responding or the URL is wrong
    json.dump([{'field':'test_smarthost','parameter':'test_smarthost','value':err,'error':'connection_timeout_error'}],fp=sys.stdout, default=str)
    sys.exit(6)
