#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import agent
import agent.tasks
import os
import sys
import json



agent_id = os.environ['AGENT_ID']
data = json.load(sys.stdin)

values = {
    "port": data['port'],
    "host": data['host'],
    "username": data['username'],
    "password": data['password'],
    "enabled": '1' if data['enabled'] else '0',
    "tls": '1' if data['tls'] else '0',
    "tls_verify": '1' if data['tls_verify'] else '0'
}

# Advertise the smarthost changes:
rdb = agent.redis_connect(privileged=True)
trx = rdb.pipeline()
trx.hset(agent_id + '/smarthost', mapping=values)
trx.publish(agent_id + '/event/smarthost-changed', json.dumps({
    'key': agent_id + '/smarthost',
}))
trx.execute()
