#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import agent
import agent.tasks
import os
import sys
import json


data = json.load(sys.stdin)

SmartHostName = data.get("SmartHostName")
SmartHostPassword = data.get("SmartHostPassword")
SmartHostPort = data.get("SmartHostPort")
SmartHostStatus = data.get("SmartHostStatus")
SmartHostUsername = data.get("SmartHostUsername")
SmartHostTlsStatus = data.get("SmartHostTlsStatus")

agent_id = os.environ['AGENT_ID']

values = {
    "port": data['port'],
    "host": data['host'],
    "username": data['username'],
    "password": data['password'],
    "enabled": 'on' if data['enabled'] else 'off',
    "tls": 'on' if data['tls'] else 'off',
    "tls_verify": 'on' if data['tls_verify'] else 'off'
}

# Advertise this new account provider service instance:
rdb = agent.redis_connect(privileged=True)
trx = rdb.pipeline()
trx.hset(agent_id + '/smarthost', mapping=data)
trx.publish(agent_id + '/event/smarthost-provider-changed', json.dumps({
    'key': agent_id + '/smarthost',
}))
trx.execute()
