#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

exec 1>&2 # Do not touch the action stdout!

#
# Avoid the "traefik1" module clash with our new leader.
# Removing traefik1 closes any connection to the api-server.
#

mid=traefik1
systemctl stop user@$(id -u "${mid}")
loginctl disable-linger "${mid}"
userdel -r "${mid}"

# Ignore errors
exit 0
