#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent

request = json.load(sys.stdin)

rich_rules = request.get('rich_rules', [])


for rule in rich_rules:
    print(agent.SD_INFO + f'Removing rich-rule: {rule}', file=sys.stderr)
    agent.run_helper('firewall-cmd', '--permanent', f'--remove-rich-rule={rule}')

# Apply the configuration
agent.run_helper('firewall-cmd', '--reload').check_returncode()
