#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import sys
import json
import agent
import subprocess

request = json.load(sys.stdin)
rdb = agent.redis_connect(privileged=False)

try:
    host = subprocess.run(['hostname', '-f'], text=True, capture_output=True, check=True).stdout.strip()
except:
    host = "myserver.example.org"
ret = { "vpn": {"host": host, "port": 55820, "network": "10.5.4.0/24"} }

json.dump(ret, fp=sys.stdout)
