#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import agent
import json
import sys

data = json.load(sys.stdin)

r = agent.redis_connect(privileged=False)

if data.get("loki_url") is not None:
    agent.set_env("LOKI_URL", data["loki_url"])
else:
    agent.set_env("LOKI_URL", "")

if data.get("auth", {}).get("token") is not None:
    agent.set_env("LOKI_AUTH_TOKEN", data["auth"]["token"])
else:
    agent.unset_env("LOKI_AUTH_TOKEN")

if data.get("auth", {}).get("basic") is not None:
    agent.set_env("LOKI_AUTH_USERNAME", data["auth"]["basic"]["username"])
    agent.set_env("LOKI_AUTH_PASSWORD", data["auth"]["basic"]["password"])
else:
    agent.unset_env("LOKI_AUTH_USERNAME")
    agent.unset_env("LOKI_AUTH_PASSWORD")

if data.get("loki_instance") is not None:
    agent.set_env("LOKI_INSTANCE", data["loki_instance"])
    loki_addr = r.hget(f'module/{data["loki_instance"]}/environment', "LOKI_ADDR")
    agent.set_env("LOKI_URL", f'http://{loki_addr}:3100/loki/api/v1/push')
    #unset the auth credentials
    agent.unset_env("LOKI_AUTH_USERNAME")
    agent.unset_env("LOKI_AUTH_PASSWORD")
    agent.unset_env("LOKI_AUTH_TOKEN")
else:
    agent.set_env("LOKI_INSTANCE", "")

agent.dump_env()
