#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

# Redirect any output to the journal (stderr)
exec 1>&2

LE_EMAIL=${LE_EMAIL:-root@$(hostname -f)}
LOG_LEVEL=${LOG_LEVEL:-INFO}

# Set action weights
cat >&${AGENT_COMFD} <<EOF
set-weight 10expandconfig 1
set-weight 10pullimage 10
set-weight 20systemd 2
EOF

cat >traefik.yaml <<EOF 
defaultEntryPoints:
  - http
  - https

file: {}

log:
  level: $LOG_LEVEL

accessLog: {}

entryPoints:
  http:
   address: ":80"
  https:
   address: ":443"

providers:
  redis:
    rootKey: "${AGENT_ID}/kv"
    endpoints:
      - "127.0.0.1:6379"

tls:
  certResolver: letsencrypt
  options: {}

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${LE_EMAIL}
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: http
      tlsChallenge: false
EOF
