#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Generate a self-signed certificate that includes the current machine FQDN
# and all machine IPs
#

set -e

# Redirect any output to the journal (stderr)
exec 1>&2

NAME="selfsigned"
FQDN="$(hostname -f).test"
addresses=''

# Do not override existing certs
if [ -e $NAME.crt ] && [ -e $NAME.key ]; then
    exit 0
fi

for ip in $(ip -json addr show | jq -r '.[].addr_info | .[].local')
do
    addresses="$addresses,IP:$ip"
done

openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes -keyout selfsigned.key -out selfsigned.crt -subj "/CN=$FQDN"  -addext "subjectAltName=DNS:localhost,DNS:$FQDN$addresses"
