#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

# Redirect any output to the journal (stderr)
exec 1>&2

# Ensure the configuration key for Traefik exists
redis-exec SETNX "${AGENT_ID}/kv" ""

# XXX configure access to the API server
redis-exec SET "${AGENT_ID}/kv/http/services/api-server/loadBalancer/servers/0/url" "http://127.0.0.1:8080"
redis-exec SET "${AGENT_ID}/kv/http/routers/api-server/rule" 'PathPrefix(`/api/`, `/ws/`, `/docs/`)'
redis-exec SET "${AGENT_ID}/kv/http/routers/api-server/service" "api-server"

# Enable and start the service
systemctl --user enable --now traefik.service
