#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import cluster.grants
import agent
import os

#
# Allow other modules to call our set-* actions from their "create-module" implementations
#

rdb = agent.redis_connect(privileged=True)
cluster.grants.grant(
    rdb,
    action_clause="set-*",
    on_clause=os.environ['AGENT_ID'],
    to_clause="create-module",
)
