#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
        "DOKUWIKI_EMAIL",
        "DOKUWIKI_FULL_NAME",
        "DOKUWIKI_IMAGE",
        "DOKUWIKI_PASSWORD",
        "DOKUWIKI_USERNAME",
        "DOKUWIKI_WIKI_NAME",
        "PHP_ENABLE_OPCACHE",
        "PHP_MEMORY_LIMIT",
        "TRAEFIK_HOST",
        "TRAEFIK_HTTP2HTTPS",
        "TRAEFIK_LETS_ENCRYPT",
    ]:
    agent.set_env(evar, original_environment[evar])

agent.dump_env()
