#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import agent
import sys
import os
import agent.tasks

rdb = agent.redis_connect()

modules = []
for mf in rdb.scan_iter('module/*/flags'):
    flags = rdb.smembers(mf)
    if 'core_module' in flags:
        continue

    module_id = mf.removeprefix('module/').removesuffix('/flags')
    modules.append(module_id)

step = len(modules)
start = 5
for module in modules:
    upd_module_result = agent.tasks.run("cluster", "update-module",
        data={"instances": [module]}, 
        endpoint="redis://cluster-leader",
        progress_callback=agent.get_progress_callback(start, start + step)
    )
    start = start + step + 1
    agent.assert_exp(upd_module_result['exit_code'] == 0)
