#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import agent
import json

#
# Sample input
#{
#    "user": "admin",
#    "revoke": [{"role":"owner",  "on":"*"}],
#    "grant":  [{"role":"reader", "on":"cluster"}],
#}
#

request = json.load(sys.stdin)
rdb = agent.redis_connect(privileged=True)

user = request['user']

for roledef in request['revoke']: # !!! revoke BEFORE grant
    cluster.grants.alter_user(rdb, user, True, roledef['role'], roledef['on'])

for roledef in request['grant']:
    cluster.grants.alter_user(rdb, user, False, roledef['role'], roledef['on'])