#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

if [[ -t 0 ]]; then
    with_tty=1
fi

hipriv="/var/lib/nethserver/cluster/state/agent.env"
lopriv="/var/lib/nethserver/node/state/agent.env"
mypriv=~/.config/state/agent.env

source="/etc/nethserver/agent.env"

# Attempt to get maximum privileges on Redis DB connection
if [[ -r "${hipriv}" ]]; then
    source "${hipriv}"
elif [[ -r "${lopriv}" ]]; then
    source "${lopriv}"
elif [[ -r "${mypriv}" ]]; then
    source "${mypriv}"
else
    REDIS_USER=default
    REDIS_PASSWORD=nopass
fi


redis_host="${REDIS_ADDRESS%:*}"
redis_host="${redis_host:-127.0.0.1}"
redis_user="${REDIS_USER:-$AGENT_ID}"

export REDISCLI_AUTH="${REDIS_PASSWORD}"

if [[ $(id -u) == 0 ]]; then
    # For the root user, spawn a redis-cli command in the rootfull Redis container
    exec podman exec -e REDISCLI_AUTH -i ${with_tty:+-t} redis redis-cli -h "${redis_host}" --user "${redis_user}" "${@}"
else
    # For non-root users, run a temporary container
    exec podman run -e REDISCLI_AUTH -i ${with_tty:+-t} --network=host --rm ghcr.io/nethserver/redis:latest redis-cli -h "${redis_host}" --user "${redis_user}" "${@}"
fi
