#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# XXX temporary implementation!!!

import sys
import agent
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('module')
parser.add_argument('--no-preserve', dest='preserve_data', default=True, action='store_false')
args = parser.parse_args()

rdb = agent.redis_connect(privileged=True)

exit_code, output, error = agent.run_subtask(rdb,
    agent_prefix='cluster',
    action='remove-module',
    input_obj={
        'module_id': args.module,
        'preserve_data': args.preserve_data,
    },
)

sys.stdout.write(output)
sys.stderr.write(error)
exit(exit_code)
