#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import agent
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('user')

args = parser.parse_args()

rdb = agent.redis_connect(privileged=True)

# Create the admin user and set a password
exit_code, output, error = agent.run_subtask(rdb,
    agent_prefix='cluster',
    action='remove-user',
    input_obj= {
        "user": args.user,
    },
)
if exit_code != 0:
    print("The action remove-user has failed:")
    sys.stdout.write(output)
    sys.stderr.write(error)
    sys.exit(exit_code)