#!/usr/local/bin/runagent python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import agent.tasks
import agent

rdb = agent.redis_connect(privileged=True)

# Prepare a list of tasks to update VPN routes on existing nodes
update_routes_tasks = [{
    'agent_id': knode.removesuffix('/vpn'),
    'action': 'update-routes',
    'data': {},
} for knode in rdb.scan_iter('node/*/vpn')] # It's ok, the new node record is still not present.

node_errors = agent.tasks.runp_brief(
    update_routes_tasks,
    extra={
        'title': "node/*/update-routes",
        'description': "update-routes command",
        'isNotificationHidden': False,
    },
    endpoint="redis://cluster-leader",
)
agent.assert_exp(node_errors == 0)
