#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Delete traefik virtual host
# Input example:
#
#  {"instance": "module1"}
#

import json
import sys
import os
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

agent_id = os.getenv("AGENT_ID", "")
if not agent_id:
    raise Exception("AGENT_ID not found inside the environemnt")

# Connect to redis
r = agent.redis_connect(privileged=True)

# Prepare common key prefix
prefix=f'{agent_id}/kv/http'
router=f'{prefix}/routers/{data["instance"]}-http'
router_s=f'{prefix}/routers/{data["instance"]}-https'

# Setup HTTP ans HTTPS routers
r.delete(f'{prefix}/services/{data["instance"]}/loadBalancer/servers/0/url')
r.delete(f'{router}/service')
r.delete(f'{router}/entrypoints')
r.delete(f'{router}/rule')
r.delete(f'{router_s}/entrypoints')
r.delete(f'{router_s}/rule')
r.delete(f'{router_s}/tls')
r.delete(f'{router_s}/service')
r.delete(f'{router_s}/tls/domains/0/main')
r.delete(f'{router_s}/tls/certresolver')
r.delete(f'{router}/middlewares/0')
