#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent
from agent.ldapproxy import Ldapproxy
from agent.ldapclient import Ldapclient, LdapclientEntryNotFound

request = json.load(sys.stdin)

domain = Ldapproxy().get_domain(request['domain'])
user = request['user']

try:
    ouser = Ldapclient.factory(**domain).get_user(user)
except LdapclientEntryNotFound:
    agent.set_status('validation-failed')
    json.dump([{'field':'user', 'parameter':'user','value': user, 'error':'user_not_found'}], fp=sys.stdout)
    sys.exit(2)

json.dump({"user":ouser}, fp=sys.stdout)
