#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import sys
import json
import agent
import cluster.grants

rdb = agent.redis_connect(privileged=False)

repositories = []

# Grant the owner role to cluster owners on the new module
for m in rdb.scan_iter('cluster/repository/*'):
    repo = rdb.hgetall(m)
    repositories.append({"name" : os.path.basename(m), "url": repo["url"], "testing": (repo["testing"] == "1"), "status": (repo["status"] == "1")})

json.dump(repositories, fp=sys.stdout)
