#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent
import redis
import socket
import hashlib
import subprocess
import agent.tasks
import os

rdb = agent.redis_connect(privileged=True)

cluster_ui_name = rdb.get(f"cluster/ui_name") or ""
leader_id = int(rdb.hget("cluster/environment", "NODE_ID"))
local_id = int(os.environ['NODE_ID'])
local_public_key = rdb.hget(f"node/{local_id}/vpn", "public_key")

ret = { 'initialized': False, 'leader': False, 'nodes': [], 'leader_url': '', 'default_password': False, 'ui_name': cluster_ui_name, }
vpn = {}

default_password = hashlib.sha256(b'Nethesis,1234').hexdigest()
admin = rdb.acl_getuser('admin')
for p in admin['passwords']:
    if p == default_password:
        ret['default_password'] = True

network = rdb.get('cluster/network')
if network is not None:
    ret["initialized"] = True
    # The leader must have a public endpoint:
    leader_hostname, _ = rdb.hget(f"node/{leader_id}/vpn", "endpoint").split(":", 1)
    ret['leader_url'] = f'https://{leader_hostname}/cluster-admin/'
    ret['leader'] = local_id == leader_id
    for node in rdb.scan_iter('node/*/vpn'):
        node_id = node.split('/')[1]
        ovpn = rdb.hgetall(node)
        kvpn = ovpn['public_key']
        if rdb.sismember(f'node/{node_id}/flags', 'nomodules'):
            continue
        node_ui_name = rdb.get(f"node/{node_id}/ui_name") or ""
        vpn[kvpn] = {'id': int(node_id), 'ui_name': node_ui_name, 'online': False, 'local': False, 'vpn': {
            'ip_address': ovpn['ip_address'],
            'listen_port': int(ovpn['listen_port']),
            'public_key': ovpn['public_key'],
            'endpoint': '',
        }}
        try:
            get_info_result = agent.tasks.run(
                agent_id=f'node/{node_id}',
                action='get-info',
                endpoint="redis://cluster-leader",
            )
        except Exception as ex:
            print(f'Error executing task get-info on node/{node_id}', ex, file=sys.stderr)
            vpn[kvpn]['online'] = False
            continue
        if get_info_result['exit_code'] == 0:
            vpn[kvpn]['online'] = True
            for key in get_info_result['output'].keys():
                vpn[kvpn][key] = get_info_result['output'][key]

else:
    json.dump(ret, fp=sys.stdout)
    sys.exit(0)

i = 0
proc = subprocess.Popen(['/usr/bin/wg', 'show', 'wg0', 'dump'],stdout=subprocess.PIPE)
for line in proc.stdout.readlines():
    parts = line.decode().rstrip().split("\t")
    if i == 0:
        vpn[local_public_key]['vpn']['public_key'] = parts[1]
        vpn[local_public_key]['local'] = True
    else:
        kvpn = parts[0]
        if not kvpn in vpn:
            continue # ignore unknown VPN peers
        endpoint = parts[2].partition(':')[0]
        if endpoint == '(none)':
            endpoint = ''
        vpn[kvpn]['vpn']['endpoint'] = endpoint
        vpn[kvpn]['vpn']['last_seen'] = int(parts[4])
        vpn[kvpn]['vpn']['rcvd'] = int(parts[5])
        vpn[kvpn]['vpn']['sent'] = int(parts[6])
        vpn[kvpn]['vpn']['keepalive'] = int(parts[7])

    i = i+1

for i in vpn.values():
    ret['nodes'].append(i)

json.dump(ret, fp=sys.stdout)
