#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent

request = json.load(sys.stdin)
rdb = agent.redis_connect(privileged=True)

if 'apply_updates_is_active' in request:
    rdb.hset('cluster/apply_updates', 'is_active', '1' if request['apply_updates_is_active'] else '0')
    # Align the apply-updates.timer status with the is_active flag just written:
    agent.run_helper('systemctl', 'start', 'check-subscription')

instances = request.get('instances', {})
if instances:
    unknown_instances = [instance_id for instance_id in instances if not rdb.hexists('cluster/module_node', instance_id)]
    if unknown_instances:
        agent.set_status('validation-failed')
        json.dump([{
            'field': 'instances',
            'parameter': 'instances',
            'value': unknown_instances,
            'error': 'instance_not_found',
        }], fp=sys.stdout)
        sys.exit(2)
    rdb.hset('cluster/module_automatic_update', mapping={
        instance_id: ('1' if enabled else '0') for instance_id, enabled in instances.items()
    })
