#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import agent.volumes
import json
import sys
import os

def main():
    mountpoints = agent.volumes.get_base_paths()
    for mp in mountpoints:
        mp["ui_name"] = mp["label"] or os.path.basename(mp["path"])
    json.dump({"mountpoints":mountpoints}, fp=sys.stdout)

if __name__ == "__main__":
    main()
