#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent

request = json.load(sys.stdin)
rdb = agent.redis_connect(privileged=False)

ret = []
for kfav in rdb.smembers('cluster/favorites'):
    # skip non-existing instances
    image_url = rdb.hget(f"module/{kfav}/environment", "IMAGE_URL")
    if image_url:
        ret.append({
            'id': kfav,
            'module': agent.get_image_name_from_url(image_url),
        })

json.dump(ret, fp=sys.stdout)
