#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import subprocess

request = json.load(sys.stdin)
name = request['name']

# Check if firewalld is running
state_p = subprocess.run(['firewall-cmd', '--state'])
if state_p.returncode == 0:
    fw_cmd = ['firewall-cmd', '--permanent']
    fw_running = True
else:
    fw_cmd = ['firewall-offline-cmd']
    fw_running = False

# Delete the service, it will be automatically removed from all zones
subprocess.run(fw_cmd + [f'--delete-service={name}'], check = True)

# Apply the configuration
if fw_running:
    subprocess.run(['firewall-cmd', '--reload'], check = True)
