#!/bin/bash

#
# Set env file
#

mid=$(id -un)

# Set defaults
NEXTCLOUD_ADMIN_USER="admin"
NEXTCLOUD_ADMIN_PASSWORD="Nethesis,1234"
NEXTCLOUD_TRUSTED_DOMAINS="nextcloud."$(hostname -f)" localhost"

# Read nextcloud config
source <(redis-hgetall "module/${mid}/module.env")

cat > ~/params.env <<EOF
NEXTCLOUD_ADMIN_USER=$NEXTCLOUD_ADMIN_USER
NEXTCLOUD_ADMIN_PASSWORD=$NEXTCLOUD_ADMIN_PASSWORD
NEXTCLOUD_TRUSTED_DOMAINS=$NEXTCLOUD_TRUSTED_DOMAINS
EOF
