#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import sys
import json
import agent
import subprocess
from datetime import datetime

request = json.load(sys.stdin)

# source
repository = request['repository']
path = request['path']

# Privileged connection for access to private/* keys:
rdb = agent.redis_connect(privileged=True)

pret = agent.run_restic(rdb, repository, path, ["--workdir=/srv"], ["snapshots", "--json"], text=True, encoding='utf-8', stdout=subprocess.PIPE)
if pret.returncode == 0:
    snapshots = []
    for el in json.loads(pret.stdout):
        time = int(datetime.fromisoformat(el['time']).timestamp())
        snapshots.append({'timestamp': time, 'id': el['id']})
    print(json.dumps(snapshots))
else:
    # Restic error message is sent through stderr as-is (in JSON format).
    sys.exit(1)
