#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

exec 1>&2
set -e

# When a new DC is added to our domain it invokes this action so we can
# update our configuration files.

read ipaddress hostname <<<$(jq -r '.ipaddress, "\t", .hostname')

# Persist the new DC address for future containers
echo "${ipaddress:?} ${hostname:?}" >> hosts
echo "nameserver ${ipaddress:?}" >> resolv.conf

# Update the running container configuration
cat hosts | podman exec ${MODULE_ID} sh -c "cat - >/etc/hosts"
cat resolv.conf | podman exec ${MODULE_ID} sh -c "cat - >/etc/resolv.conf"
