#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent

request = json.load(sys.stdin)

name = request["name"]
content = request["content"]

if name == "default_en" or name == "default_it":
    agent.set_status('validation-failed')
    json.dump([{'field':'name', 'parameter':'name','value': name, 'error':'template_not_allowed'}], fp=sys.stdout)
    # we print the error message in logs
    print(agent.SD_WARNING + f"Error: the template {name} is not allowed", file=sys.stderr)
    sys.exit(3)

rdb = agent.redis_connect(privileged=True)
if rdb.hget(f"cluster/password_warning/templates", name):
    agent.set_status('validation-failed')
    json.dump([{'field':'name', 'parameter':'name','value': name, 'error':'template_already_exists'}], fp=sys.stdout)
    # we print the error message in logs
    print(agent.SD_WARNING + f"Error: the template {name} already exists", file=sys.stderr)
    sys.exit(3)

rdb.hset(f"cluster/password_warning/templates", name, content)