#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent
import subprocess
import semver

request = json.load(sys.stdin)
core_url = request['core_url']
force_update = request.get("force", False)

agent.set_weight(os.path.basename(__file__), 2)

try:
    core_env = agent.read_envfile('/etc/nethserver/core.env')
    aver = semver.parse_version_info(core_env['CORE_IMAGE'].split(':')[-1])
    bver = semver.parse_version_info(core_url.split(':')[-1])
except ValueError:
    print(agent.SD_WARNING + 'Cannot parse semantic version information from core image tags. Assuming a "minor" update type is occurring', file=sys.stderr)
    aver = semver.parse_version_info('0.0.0')
    bver = semver.parse_version_info('0.1.0')

if force_update == False and aver >= bver:
    print('The new core image does not update the current one. Nothing to do.', file=sys.stderr)
    sys.exit(0)

if force_update:
    podman_pull_command = ['podman', 'pull']
else:
    podman_pull_command = ['podman-pull-missing']

agent.run_helper(*podman_pull_command, core_url,
    progress_callback=agent.get_progress_callback(0,40)
).check_returncode()

# Get the old Podman image Id
with subprocess.Popen(['podman', 'image', 'inspect', '-f', '{{.Id}}', core_env['CORE_IMAGE']], stdout=subprocess.PIPE, stderr=sys.stderr) as proc:
    agent.set_env('PREV_IMAGE_ID', proc.stdout.read().rstrip())

# Parse the image labels
with subprocess.Popen(['podman', 'image', 'inspect', core_url], stdout=subprocess.PIPE, stderr=sys.stderr) as proc:
    inspect = json.load(proc.stdout)
    inspect_labels = inspect[0]['Labels']
    inspect_image_id = inspect[0]['Id']
    inspect_image_digest = inspect[0]['Digest']
    inspect_image_repodigest = inspect[0]['RepoDigests'][0]
    agent.set_env('IMAGE_ID', inspect_image_id)

if 'org.nethserver.images' in inspect_labels:
    extra_images = inspect_labels['org.nethserver.images'].split()
else:
    extra_images = []

print('Core image Id         : ', inspect_image_id, file=sys.stderr)
print('Core image Digest     : ', inspect_image_digest, file=sys.stderr)
print('Core image RepoDigest : ', inspect_image_repodigest, file=sys.stderr)
print('Core image extras     : ', extra_images, file=sys.stderr)

agent.run_helper(*podman_pull_command, *extra_images,
    progress_callback=agent.get_progress_callback(41,70)
).check_returncode()

# NOTE: `install-coreimage` also installs and cleans up scripts under
# update-core.d/. When the next step runs, only scripts from the new image
# are executed
agent.run_helper('install-coreimage', core_url,
    progress_callback=agent.get_progress_callback(71,99)
).check_returncode()

agent.run_helper('systemctl', 'daemon-reload')
