#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2
set -e

# Clean up local images that are no longer required by the new core
# version

export LC_ALL=C # required by sort for portability

source /etc/nethserver/core.env

# Find the images that are no longer required
diff <(
    echo "${IMAGE_ID}"
    podman inspect -f json "${IMAGE_ID:-none}" | \
            jq -r '.[0].Config.Labels."org.nethserver.images" | split(" ") | join("\n")' | \
            sort -c
) <(
    echo "${PREV_IMAGE_ID}"
    podman inspect -f json "${PREV_IMAGE_ID:-none}" | \
            jq -r '.[0].Config.Labels."org.nethserver.images" | split(" ") | join("\n")' | \
            sort -c
) | sed -n '/< / s/< //p' | \
    xargs -t -- podman rmi 2>/dev/null || :
