#!/bin/bash -x

#
# Setup wireguard master node
#

VPN_OUT_DIR=/etc/wireguard
VPN_CONF=$VPN_OUT_DIR/wg0.conf
mkdir -p $VPN_OUT_DIR
chmod 700 $VPN_OUT_DIR

hostname=$(hostname -s)

# Private key should be passed as event argument
private_key=$1

# Load VPN config variables
source <(redis-hgetall "node/${hostname}/vpn")

# Save private key
umask 0077
echo $private_key > $VPN_OUT_DIR/privatekey
umask 0022

# Generate configuration
rm -f $VPN_CONF
cat > $VPN_OUT_DIR/wg0.conf << EOF
[Interface]
Address = $IP_ADDRESS/24
PrivateKey = $private_key
ListenPort = $LISTEN_PORT
EOF

systemctl stop wg-quick@wg0 &>/dev/null
systemctl enable --now wg-quick@wg0
