#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent
import os

request = json.load(sys.stdin)

host = request['host']
port = int(request['port'])
tls  = bool(request['tls'])
schema = request['schema']
backend = request['backend']
tls_verify = bool(request['tls_verify'])
base_dn = request.get('base_dn', '')
bind_dn = request.get('bind_dn', '')
bind_password = request.get('bind_password', '')

agent.set_env('BACKEND', backend)
agent.set_env('SCHEMA', schema)
agent.set_env('BIND_PASSWORD', bind_password)
agent.set_env('TLS', '1' if tls else '')
agent.set_env('TLS_VERIFY', '1' if tls_verify else '')
agent.set_env('URI', f'{"ldaps" if tls else "ldap"}://{host}:{port}')
agent.set_env('HOST', host)
agent.set_env('PORT', port)
#
# LDAP* variables can be passed to OpenLDAP libraries,
# as documented by LDAP.CONF(5) man page. Use the same variables
# as configuration sources for other clients.
#
agent.set_env('LDAPURI', 'ldap://127.0.0.1:' + os.environ['TCP_PORT'])
agent.set_env('LDAPHOST', '127.0.0.1')
agent.set_env('LDAPPORT', os.environ['TCP_PORT'])
agent.set_env('LDAPBINDDN', bind_dn)
agent.set_env('LDAPTLS_REQCERT', 'try' if tls_verify else 'never')
agent.set_env('LDAPBASE', base_dn)

agent.dump_env()

json.dump({}, fp=sys.stdout)
