#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent
import os

request = json.load(sys.stdin)

host = request['host']
port = int(request['port'])
tls  = bool(request['tls'])
schema = request['schema']
backend = request['backend']
tls_verify = bool(request['tls_verify'])

agent.set_env('BACKEND', backend)
agent.set_env('SCHEMA', schema)
agent.set_env('LDAPHOST', host)
agent.set_env('LDAPPORT', port)
agent.set_env('LDAPTLS', 'on' if tls else 'off')
agent.set_env('LDAPTLS_VERIFY', 'on' if tls_verify else 'off')
agent.set_env('LDAPTLS_VERIFY_DEPTH', '2') # Hardcoded default

agent.dump_env()

json.dump({}, fp=sys.stdout)
