#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Read Dokuwiki configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}

# Read current configuration from Redis
env = f'module/{os.environ["MODULE_ID"]}/environment'
rdb = agent.redis_connect()
config["wiki_name"] = rdb.hget(env, "DOKUWIKI_WIKI_NAME")
config["username"] = rdb.hget(env, "DOKUWIKI_USERNAME");
config["password"] = rdb.hget(env, "DOKUWIKI_PASSWORD"); 
config["email"] = rdb.hget(env, "DOKUWIKI_EMAIL");
config["user_full_name"] = rdb.hget(env, "DOKUWIKI_FULL_NAME");
config["host"] =  rdb.hget(env, "TRAEFIK_HOST");
config["http2https"] =  rdb.hget(env, "TRAEFIK_HTTP2HTTPS") == "True";
config["lets_encrypt"] =  rdb.hget(env, "TRAEFIK_LETS_ENCRYPT") == "True";

# Dump the configuratio to stdou
json.dump(config, fp=sys.stdout)
