#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent

request = json.load(sys.stdin)

rich_rules = request.get('rich_rules', [])
if not isinstance(rich_rules, list) or len(rich_rules) == 0:
    agent.assert_exp(False, 'rich_rules must be a non-empty array')

for rule in rich_rules:
    # Apply rule for both families if not already family-qualified
    print(agent.SD_INFO + f'Adding rich-rule: {rule}', file=sys.stderr)
    agent.run_helper('firewall-cmd', '--permanent', f'--add-rich-rule={rule}')

# Apply the configuration
agent.run_helper('firewall-cmd', '--reload').check_returncode()
