#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent
import subprocess

request = json.load(sys.stdin)
rdb = agent.redis_connect(privileged=False)

name = request['repository']
url = rdb.hget(f"cluster/backup_repository/{name}", "url").split(":")

backups = dict()
cmd = ["rclone", "--config", f'/var/lib/nethserver/backup_repository/{name}/rclone.conf', 'lsjson', '--no-mimetype', '--no-modtime' ]
proc = subprocess.run(cmd + [f'{url[1]}:/{url[1]}'], capture_output=True)
for d in json.loads(proc.stdout):
    pdir = subprocess.run(cmd +  [f'{url[1]}:/{url[1]}/{d["Path"]}'], capture_output=True)
    if d['Path'] not in backups:
        backups[d['Path']] = []
    for backup in json.loads(pdir.stdout):
        backups[d['Path']].append(backup['Path'])

print(json.dumps(backups))
