#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

agent.set_weight("00validate_cluster", 0)
agent.set_weight("10validate_network", 0)
agent.set_weight("40update_cluster", 3)

request = json.load(sys.stdin)

rdb = agent.redis_connect()

network = rdb.get('cluster/network')

if network:
    agent.set_status('validation-failed')
    json.dump([{'field':'network', 'parameter':'network','value': request['network'], 'error':'cluster_network_already_set'}], fp=sys.stdout)
    sys.exit(2)
