#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

request = json.load(sys.stdin)

rdb = agent.redis_connect()

network = rdb.get('cluster/network')

if network:
    agent.set_status('validation-failed')
    json.dump([{'field':'network', 'parameter':'network','value': request['network'], 'error':'cluster_network_already_set'}], fp=sys.stdout)
    sys.exit(2)
