#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.rdb.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServerdb.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServerdb.  If not, see COPYING.
#

import sys
import ipcalc
import os
import json
import agent
import agent.tasks
import cluster.grants

request = json.load(sys.stdin)

network = request['network']
listen_port = int(request['listen_port'])

try:
    endpoint = agent.sanitize_endpoint(request['endpoint'])
except:
    json.dump({"field": "endpoint", "parameter": "endpoint", "value": request['endpoint'], "error": "endpoint_resolution_failed"}, fp=sys.stdout)
    agent.set_status('validation-failed')
    sys.exit(2)

agent.assert_exp(network)
agent.assert_exp(endpoint)
agent.assert_exp(listen_port)

public_key = agent.slurp_file('/etc/nethserver/wg0.pub')
agent.assert_exp(public_key)

NODE_ID = 1
ip_address = str(ipcalc.Network(network).network() + NODE_ID)

# Get a Redis connection
rdb = agent.redis_connect(privileged=True)

#
# Set the cluster/network and VPN settings in Redis DB
#
rdb.set('cluster/network', network)
rdb.hset(f'node/{NODE_ID}/vpn', mapping={
    "public_key": public_key,
    "ip_address": ip_address,
    "destinations": "",
    "endpoint": endpoint,
    "listen_port": listen_port,
})

# Our first Traefik instance is missing the VPN network: fix it here.
rdb.set('module/traefik1/kv/http/middlewares/ApiServerMw1/ipWhiteList/sourceRange/1', network)

# Update the cluster-localnode record in /etc/hosts
agent.run_helper('sed', '-i',
    '-e', f'/cluster-localnode$/c\{ip_address} cluster-localnode',
    '/etc/hosts').check_returncode()

#
# Apply new VPN setup
#
agent.save_wgconf(ip_address, listen_port)
agent.run_helper(*'systemctl restart wg-quick@wg0'.split(' ')).check_returncode()

#
# Bind Redis to the VPN ip_address
#
redis_bind_vpn_ip = rdb.execute_command('CONFIG SET', 'bind', f'127.0.0.1 ::1 {ip_address}')
agent.assert_exp(redis_bind_vpn_ip is True)
redis_rewrite_conf = rdb.execute_command('CONFIG REWRITE')
agent.assert_exp(redis_rewrite_conf == 'OK')

# (Samba) account provider might want to route some IP addresses through our VPN. Define a role for that:
cluster.grants.grant(rdb, action_clause="update-routes", to_clause="accountprovider", on_clause='cluster')

#
# Install ldapproxy here
#
add_module_result = agent.tasks.run(
    agent_id='cluster',
    action='add-module',
    data={
        'image': 'ghcr.io/nethserver/ldapproxy:latest',
        'node': NODE_ID,
    },
    endpoint="redis://cluster-leader",
)
agent.assert_exp(add_module_result['exit_code'] == 0)

json.dump({
    "ip_address": ip_address,
}, fp=sys.stdout)
