#!/bin/sh

echo "set-progress 25"  >&$AGENT_COMFD
read -r ack <&${AGENT_ACKFD:?}
echo "set-progress 50"  >&$AGENT_COMFD
read -r ack <&${AGENT_ACKFD:?}
echo "set-progress 75"  >&$AGENT_COMFD
read -r ack <&${AGENT_ACKFD:?}
echo "set-progress 99" >&$AGENT_COMFD
read -r ack <&${AGENT_ACKFD:?}
