#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import subprocess

# make sure the command is executed with English locale
env = os.environ.copy()
env['LANG'] = 'C'

# List the rich rules of the default (public) zone from the permanent
# configuration: it is the one written by add-rich-rules/remove-rich-rules
proc = subprocess.run(['firewall-cmd', '--permanent', '--list-rich-rules'],
                      env=env, capture_output=True, text=True, check=True)

rich_rules = [line.strip() for line in proc.stdout.split("\n") if line.strip()]

json.dump({"rich_rules": rich_rules}, fp=sys.stdout)
