#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import os
import json
import agent

request = json.load(sys.stdin)
network = request['network']
agent.assert_exp(network)
rdb = agent.redis_connect(privileged=True)
# Set the cluster/network to prevent join-cluster and create-cluster to be
# invoked again on this node, in case of join-node failure.
rdb.set('cluster/network', network)
