#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent

request = json.load(sys.stdin)


# Add port forward with rich rules
for family in ['ipv4', 'ipv6']:
    for proto in request['protocols']:
        rich_rule = [f'--remove-rich-rule=rule family={family} forward-port port={request["external_port"]} protocol={proto} to-port={request["internal_port"]}']
        if 'destination_ip' in request and request.get('destination_ip') is not None:
            rich_rule.append(f'to-addr={request["destination_ip"]}')
        print(agent.SD_INFO + f'Removing port forward for port {request["external_port"]} to port {request["internal_port"]}', file=sys.stderr)
        agent.run_helper('firewall-cmd', '--permanent', *rich_rule)

# Apply the configuration
agent.run_helper('firewall-cmd', '--reload').check_returncode()