#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

# Redirect any output to the journal (stderr)
exec 1>&2

# N is the service name
read N URL HOST

#SET traefik0/http/routers/$N-https/tls/certresolver letsencrypt
redis-exec <<EOF
MULTI
SET "${AGENT_ID}/kv/http/services/$N/loadbalancer/servers/0/url" "$URL"
SET "${AGENT_ID}/kv/http/routers/$N-http/service" "$N"
SET "${AGENT_ID}/kv/http/routers/$N-http/entrypoints" "http,https"
SET "${AGENT_ID}/kv/http/routers/$N-http/rule" "Host(\`$HOST\`)"
SET "${AGENT_ID}/kv/http/routers/$N-https/entrypoints" "http,https"
SET "${AGENT_ID}/kv/http/routers/$N-https/rule" "Host(\`$HOST\`)"
SET "${AGENT_ID}/kv/http/routers/$N-https/tls" "true"
SET "${AGENT_ID}/kv/http/routers/$N-https/service" "$N"
SET "${AGENT_ID}/kv/http/routers/$N-https/tls/domains/0/main" "$HOST"
EXEC
EOF
