#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

# Redirect any output to the journal (stderr)
exec 1>&2

# Read the following space-separated parameters:
# - N is the service name
# - URL is the backend URL
# - HOST is the virtual host name
# - LETS_ENCRYPT can be 0 or 1, if set to 1 request a valid Let's Encrypt certificate
# - FORCE_HTTPS can be 0 or 1, if set to 1 HTTP will be redirect to HTTPS
read N URL HOST LETS_ENCRYPT FORCE_HTTPS

redis-exec <<EOF
MULTI
SET "${AGENT_ID}/kv/http/services/$N/loadbalancer/servers/0/url" "$URL"
SET "${AGENT_ID}/kv/http/routers/$N-http/service" "$N"
SET "${AGENT_ID}/kv/http/routers/$N-http/entrypoints" "http,https"
SET "${AGENT_ID}/kv/http/routers/$N-http/rule" "Host(\`$HOST\`)"
SET "${AGENT_ID}/kv/http/routers/$N-https/entrypoints" "http,https"
SET "${AGENT_ID}/kv/http/routers/$N-https/rule" "Host(\`$HOST\`)"
SET "${AGENT_ID}/kv/http/routers/$N-https/tls" "true"
SET "${AGENT_ID}/kv/http/routers/$N-https/service" "$N"
SET "${AGENT_ID}/kv/http/routers/$N-https/tls/domains/0/main" "$HOST"
EXEC
EOF

if [[ "$LETS_ENCRYPT" == "1" ]]; then
    redis-exec <<EOF
SET "${AGENT_ID}/kv/http/routers/$N-https/tls/certresolver" "letsencrypt"
EOF
else
    redis-exec <<EOF
DEL "${AGENT_ID}/kv/http/routers/$N-https/tls/certresolver"
EOF
fi


if [[ "$FORCE_HTTPS" == "1" ]]; then
    redis-exec <<EOF
SET "${AGENT_ID}/kv/http/routers/$N-http/middlewares/0" "http2https-redirectscheme"
EOF
else
    redis-exec <<EOF
DEL "${AGENT_ID}/kv/http/routers/$N-http/middlewares/0"
EOF
fi
