#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import agent.tasks
import os

rdb = agent.redis_connect(privileged=True)
is_metrics_installed = rdb.exists(f"node/{os.getenv('NODE_ID')}/default_instance/metrics")

if not is_metrics_installed:
    add_module_failures = agent.tasks.runp_brief([
        {"agent_id": "cluster", "action": "add-module", "data": {
            'image': 'ghcr.io/nethserver/metrics:latest', #FIXME
            'node': int(os.getenv("NODE_ID")),
        }}],
        endpoint = "redis://cluster-leader",
    )
    agent.assert_exp(add_module_failures == 0)
