#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os
import sys
import json
import cluster.backup
import subprocess

def main():
    request = json.load(sys.stdin)
    try:
        run_validation(request)
    except subprocess.CalledProcessError as ex:
        if 'lsd' in ex.cmd:
            reason = "no_read_permission"
        elif 'rcat' in ex.cmd:
            reason = "no_write_permission"
        elif 'deletefile' in ex.cmd:
            reason = "no_delete_permission"
        else:
            reason = 'unknown'
        print(f"node {os.environ['NODE_ID']}: {reason} on destination {request['id']} (code={ex.returncode})", file=sys.stderr)
        agent.set_status('validation-failed')
        json.dump([{'field':'','parameter':'','value':{},'error':reason}], fp=sys.stdout)
        sys.exit(2)

def run_validation(request):
    rclone_args = [
        '--timeout=5s',
        '--contimeout=5s',
        '--retries=1',
        '--low-level-retries=1',
        '--retries-sleep=100ms',
    ]
    if os.getenv("DEBUG") == '1':
        rclone_args.append("-vvvv")
    rpath = request['id'] + ':' + request['basepath']
    # Test if connection and read-access is successfull
    cluster.backup.run_rclone(['lsd', rpath] + rclone_args, temp_config=request['rclone_conf_secret'], stdout=subprocess.DEVNULL, check=True)

    # Test write access, by creating and deleting a temporary file
    remote_test_file = rpath + '/' + os.environ["AGENT_TASK_ID"] + '.tmp'
    cluster.backup.run_rclone(
        ['rcat', remote_test_file] + rclone_args,
        temp_config=request['rclone_conf_secret'],
        input=b'ns8 backup destination validation\n',
        stdout=subprocess.DEVNULL,
        check=True,
    )
    cluster.backup.run_rclone(['deletefile', remote_test_file] + rclone_args, temp_config=request['rclone_conf_secret'], stdout=subprocess.DEVNULL, check=True)
    json.dump({"node_id":int(os.environ["NODE_ID"]),"id": request["id"]}, fp=sys.stdout)

if __name__ == "__main__":
    main()
