#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

exec 1>&2
set -e

cat >&"${AGENT_COMFD}" <<EOF
set-weight 01validate_ip 0
set-weight 40start_provisioning 5
EOF

read -r ipaddress < <(jq -r '.ipaddress')

# Check if ipaddress is bound to a network interface
if ! ip -o address show to "${ipaddress}/32" up | grep -q "${ipaddress}"; then
    jq -c -n --arg ipaddress "${ipaddress}" '[{"field":"ipaddress","parameter":"ipaddress","value":$ipaddress,"error":"ipaddress_does_not_exist"}]'
    echo "set-status validation-failed" >&"${AGENT_COMFD}"
    exit 2
fi

exit 0
