#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import agent
import agent.tasks
import os
import sys
import json

#
# This is a prerequisite: if IP routing is not correctly set, the DC join might fail.
#

request = json.load(sys.stdin)


ip_address = request['ipaddress']
module_id = os.environ['MODULE_ID']
node_id = int(os.environ['NODE_ID'])
agent.assert_exp(node_id > 0)

add_route_result = agent.tasks.run(
    agent_id='cluster',
    action='add-route',
    data={
        "network": ip_address + '/32',
        "node_id": node_id,
    }
)

agent.assert_exp(add_route_result['exit_code'] == 0)
