#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

mid=$(basename ${AGENT_ID})

/usr/bin/podman run -ti \
    --dns=none \
    --no-hosts \
    --network=host \
    --cap-drop=all \
    --cap-add=chown,dac_override,dac_read_search,fowner,setgid,setuid,sys_admin \
    --env ADMINPASS \
    --env ADMINUSER \
    --env NBDOMAIN \
    --env REALM \
    --hostname=${HOSTNAME} \
    --rm --name="${mid}-provision" \
    --volume=${mid}-data:/var/lib/samba:Z \
    --volume=${mid}-config:/etc/samba:Z \
    --volume=hosts:/etc/hosts:Z \
    --volume=resolv.conf:/etc/resolv.conf:Z \
    --volume=krb5.conf:/etc/krb5.conf:Z \
    ${SAMBA_IMAGE} ${PROVISION_TYPE}
