#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import agent
import agent.tasks
import sys, os
import cluster.modules

rdb = agent.redis_connect(privileged=True)

# Update all core modules
instances = dict()
for oimage in cluster.modules.list_core_modules():
    image_id = oimage['name']
    if image_id == 'core':
        continue # skip core: it is handled by another action step

    # Prepare a list of module instances that need the update
    module_instances = [oinstance['id'] for oinstance in oimage['instances'] if oinstance['update']]

    if len(module_instances) > 0: # must be not empty
        instances[image_id] = {
            'url': cluster.modules.get_latest_module(image_id, rdb),
            'instances': module_instances,
        }

update_module_tasks = []
for mid in instances.keys():
    update_module_tasks.append({
        'agent_id': 'cluster',
        "action": "update-module",
        "data": {
            "module_url": instances[mid]['url'],
            "instances":  instances[mid]['instances']
        }
    })


update_module_errors = agent.tasks.runp_brief(update_module_tasks,
    endpoint = "redis://cluster-leader",
    progress_callback=agent.get_progress_callback(75, 95),
)

agent.assert_exp(update_module_errors == 0)

json.dump({}, fp=sys.stdout)
