#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e
exec 1>&2

# Enable services at boot
systemctl --user enable pod-mail.service

# Calculate the mailbox domain name for Postfix,
# starting from the full host name assigned to the mail pod instance:
MAILBOX_DOMAIN=$(hostname -f | cut -f 2- -d ".")
HOSTNAME=$(hostname -f)
AUTH_BIND_USERDN="%u"

# Persist environment variables in Redis DB:
cat >&${AGENT_COMFD} <<EOF
set-env HOSTNAME ${HOSTNAME}
set-env AUTH_BIND_USERDN ${AUTH_BIND_USERDN}
set-env MAILBOX_DOMAIN ${MAILBOX_DOMAIN}
EOF
