name: promtail
on:
  push:
    branches:
      - main
    paths:
      - 'promtail/**'
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - 'promtail/**'

jobs:
  push_image:
    env:
      REPONAME: ${{ github.workflow }}
      IMAGETAG: ${{ github.head_ref }}
    name: 'Build ${{ github.workflow }}'
    runs-on: ubuntu-20.04
    steps:
      - id: info
        name: "Retrieve runtime information"
        run: |
          echo "::set-output name=org::$(dirname ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')"
      - id: checkout
        uses: actions/checkout@v2
      - id: build
        name: "Build the images"
        run: "cd ${REPONAME} && bash build-image.sh"
        env:
          REPOBASE: ghcr.io/${{ steps.info.outputs.org }}
      - id: push
        name: "Push the images"
        run: |
          # Push the images
          set -e
          trap 'buildah logout ghcr.io' EXIT
          buildah login -u ${{ github.actor }} --password-stdin ghcr.io <<<"${{ secrets.GITHUB_TOKEN }}"
          tag=${IMAGETAG:-latest}
          for image in ${{ steps.build.outputs.images }} ; do
              buildah push $image docker://${image}:$tag
              # Push also ns8-stable label, if tag is not a pre-release
              if echo -n "${IMAGETAG}" | grep -q -v -e '-' ; then buildah push $image docker://${image}:ns8-stable ; fi
          done
