#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent
import agent.tasks
import cluster.userdomains

request = json.load(sys.stdin)

domain = request.get('domain', '')

rdb = agent.redis_connect(privileged=True)
domains = cluster.userdomains.get_internal_domains(rdb)

if len(domain) > 0 and not domain in domains:
    agent.set_status('validation-failed')
    json.dump([{'field':'domain', 'parameter':'domain','value': domain, 'error':'domain_not_found'}], fp=sys.stdout)
    sys.exit(2)

add_result = agent.tasks.run("cluster", "add-module", data={
        'node': request['node'],
        'image': request['image'],
    },
    endpoint="redis://cluster-leader",
    progress_callback = agent.get_progress_callback(5, 98),
)

agent.assert_exp(add_result['exit_code'] == 0, "Internal provider installation failed!")
module_id = add_result['output']['module_id']
rdb.set(f'module/{module_id}/user_domain', domain)

json.dump(add_result['output'], fp=sys.stdout)
