#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import agent
import os
import json

if os.getenv('IMPORT_IMAGE_URL'):
    agent.set_status('validation-failed')
    json.dump([{'field':'none', 'parameter':'none','value': '', 'error':'module_already_imported'}], fp=sys.stdout)
    sys.exit(2)
