#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import agent
import os
import json

agent.set_weight(os.path.basename(__file__), 0) # Validation step, no task progress at all

if os.getenv('IMPORT_IMAGE_URL'):
    agent.set_status('validation-failed')
    json.dump([{'field':'none', 'parameter':'none','value': '', 'error':'module_already_imported'}], fp=sys.stdout)
    sys.exit(2)
