#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import agent
import json
import subprocess
import os

request = json.load(sys.stdin)
is_rootfull = (os.geteuid() == 0)
module_id = os.environ['MODULE_ID']

if is_rootfull:
    create_volumes = set([f'{module_id}-{xvol}' for xvol in request['volumes']])
else:
    create_volumes = set(request['volumes'])

with subprocess.Popen(['podman', 'volume', 'ls', '--format=json'], stdout=subprocess.PIPE) as vproc:
    for vobj in json.load(vproc.stdout):
        create_volumes.discard(vobj['Name']) # Discard volume if already exists

for xvol in create_volumes:
    agent.run_helper('podman', 'volume', 'create', xvol).check_returncode()
