#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

try:
    agent.deallocate_ports("tcp", os.environ['MODULE_ID'] + "_rsync")
except:
    pass
